// src/lib/aircraft.ts
export type Aircraft = {
  name: string
  type: 'jet' | 'turbo' | 'piston'
  tas: number      // kt — true airspeed cruise
  pax: number
  range: number    // nm
  initK: number    // $K
  fixK: number     // $K/yr
  varH: number     // $/hr
  rating: boolean  // type rating required
  fuel: 'Jet-A' | 'AvGas'
  gear: 'retractable' | 'tricycle' | 'tailwheel'
  engines: 1 | 2 | 3 | 4
}

// Fallback per category (used for wind ring when no aircraft selected)
export const TAS: Record<Aircraft['type'], number> = {
  jet: 450, turbo: 280, piston: 130
}

export const AC: Aircraft[] = [

  // ── Aero ─────────────────────────────────────────────────────
  { name:'Aero Commander 500',         type:'piston',tas:165, pax:5,  range:626,  initK:45,    fixK:14,   varH:72,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aero Commander 500B',        type:'piston',tas:170, pax:5,  range:642,  initK:50,    fixK:15,   varH:75,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aero Commander 500S Shrike', type:'piston',tas:190, pax:6,  range:758,  initK:75,    fixK:17,   varH:82,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aero Commander 560 Twin',    type:'piston',tas:175, pax:5,  range:669,  initK:60,    fixK:16,   varH:80,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aero Commander 680 Super',   type:'piston',tas:200, pax:7,  range:850, initK:90,    fixK:19,   varH:90,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aero Commander 690 Turbo',   type:'turbo', tas:260, pax:8,  range:1170, initK:350,   fixK:80,   varH:400,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Aeronca ─────────────────────────────────────────────────────
  { name:'Aeronca Champ 7AC',          type:'piston',tas:85,  pax:2,  range:286,  initK:25,    fixK:5,    varH:22,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Aeronca Chief 11AC',         type:'piston',tas:80,  pax:2,  range:240,  initK:22,    fixK:5,    varH:20,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Aeronca Defender L-16',      type:'piston',tas:90,  pax:2,  range:262,  initK:30,    fixK:6,    varH:24,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Aeronca Sedan 15AC',         type:'piston',tas:105, pax:4,  range:371,  initK:38,    fixK:8,    varH:32,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Aerostar ─────────────────────────────────────────────────────
  { name:'Aerostar 600',               type:'piston',tas:225, pax:5,  range:1031, initK:90,    fixK:19,   varH:92,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aerostar 601',               type:'piston',tas:228, pax:5,  range:1079, initK:95,    fixK:19,   varH:93,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aerostar 601P',              type:'piston',tas:210, pax:5,  range:1142, initK:100,   fixK:20,   varH:95,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aerostar 602P',              type:'piston',tas:225, pax:5,  range:1181, initK:120,   fixK:21,   varH:98,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aerostar 700',               type:'piston',tas:230, pax:5,  range:1228, initK:140,   fixK:22,   varH:100,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Aerostar 700P',              type:'piston',tas:235, pax:5,  range:1274, initK:150,   fixK:23,   varH:102,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  // ── American ─────────────────────────────────────────────────────
  { name:'American Champion 8KCAB Decathlon',   type:'piston',tas:128,pax:2,range:384,initK:150, fixK:10, varH:47,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'American Champion Citabria 7ECA',     type:'piston',tas:100,pax:2,range:375,initK:65,  fixK:9,  varH:42,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'American Champion Citabria 7GCBC',    type:'piston',tas:105,pax:2,range:391,initK:80,  fixK:9,  varH:44,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'American Champion Denali Scout 210',  type:'piston',tas:115,pax:2,range:494,initK:280, fixK:12, varH:55,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'American Champion Scout 180',         type:'piston',tas:108,pax:2,range:469,initK:220, fixK:11, varH:52,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'American Champion Super Decathlon',   type:'piston',tas:130,pax:2,range:402,initK:160, fixK:10, varH:48,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Aviat ─────────────────────────────────────────────────────
  { name:'Aviat Husky A-1A',           type:'piston',tas:118, pax:2,  range:562,  initK:190,   fixK:10,   varH:48,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Aviat Husky A-1B',           type:'piston',tas:120, pax:2,  range:590,  initK:210,   fixK:10,   varH:50,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Aviat Husky A-1C-180',       type:'piston',tas:122, pax:2,  range:608,  initK:240,   fixK:11,   varH:52,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Aviat Pitts S-2B',           type:'piston',tas:150, pax:2,  range:188,  initK:140,   fixK:11,   varH:55,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Aviat Pitts S-2C',           type:'piston',tas:155, pax:2,  range:164,  initK:220,   fixK:12,   varH:58,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Beechcraft ─────────────────────────────────────────────────────
  { name:'Beechcraft Baron 55',            type:'piston',tas:188, pax:5,  range:859, initK:85,    fixK:17,   varH:88,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Baron 56TC',          type:'piston',tas:210, pax:5,  range:942, initK:200,   fixK:24,   varH:112,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Baron 58',            type:'piston',tas:198, pax:5,  range:1052, initK:280,   fixK:25,   varH:110,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Baron 58P pressurized',type:'piston',tas:191,pax:5, range:870, initK:400,   fixK:28,   varH:120,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Baron 58TC turbo',    type:'piston',tas:220, pax:5,  range:885, initK:350,   fixK:26,   varH:115,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Baron B55',           type:'piston',tas:190, pax:5,  range:808,  initK:95,    fixK:18,   varH:90,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Baron E55',           type:'piston',tas:195, pax:5,  range:854, initK:180,   fixK:20,   varH:95,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Baron G58',           type:'piston',tas:202, pax:6,  range:1328, initK:1200,  fixK:35,   varH:150,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Beechjet 400A',       type:'jet',  tas:448, pax:8,  range:1236, initK:1500,  fixK:120,  varH:780,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft Bonanza 35',          type:'piston',tas:160, pax:4,  range:580,  initK:50,    fixK:16,   varH:80,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza A35',         type:'piston',tas:162, pax:4,  range:598,  initK:52,    fixK:16,   varH:80,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza A36TC',       type:'piston',tas:180, pax:6,  range:1065, initK:750,   fixK:24,   varH:115,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza B35',         type:'piston',tas:163, pax:4,  range:598,  initK:53,    fixK:16,   varH:80,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza C35',         type:'piston',tas:165, pax:4,  range:616,  initK:55,    fixK:16,   varH:80,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza D35',         type:'piston',tas:166, pax:4,  range:616,  initK:56,    fixK:16,   varH:80,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza E35',         type:'piston',tas:167, pax:4,  range:625,  initK:57,    fixK:16,   varH:82,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza F33A',        type:'piston',tas:174, pax:4,  range:790,  initK:180,   fixK:18,   varH:92,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza F35',         type:'piston',tas:168, pax:4,  range:624,  initK:58,    fixK:16,   varH:82,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza G35',         type:'piston',tas:169, pax:4,  range:633,  initK:60,    fixK:17,   varH:83,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza G36',         type:'piston',tas:176, pax:6,  range:868, initK:680,   fixK:22,   varH:105,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza H35',         type:'piston',tas:170, pax:4,  range:632,  initK:62,    fixK:17,   varH:84,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza K35',         type:'piston',tas:172, pax:4,  range:651,  initK:64,    fixK:17,   varH:85,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza M35',         type:'piston',tas:173, pax:4,  range:660,  initK:66,    fixK:17,   varH:86,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza N35',         type:'piston',tas:174, pax:4,  range:670,  initK:68,    fixK:17,   varH:87,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza P35',         type:'piston',tas:175, pax:4,  range:679,  initK:70,    fixK:17,   varH:88,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza S35',         type:'piston',tas:176, pax:4,  range:688,  initK:75,    fixK:18,   varH:88,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza V35',         type:'piston',tas:178, pax:4,  range:696,  initK:80,    fixK:18,   varH:90,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza V35A',        type:'piston',tas:179, pax:4,  range:706,  initK:85,    fixK:18,   varH:91,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Bonanza V35B',        type:'piston',tas:180, pax:4,  range:715,  initK:90,    fixK:18,   varH:92,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Debonair 33',         type:'piston',tas:170, pax:4,  range:722,  initK:70,    fixK:17,   varH:85,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Duchess 76',          type:'piston',tas:160, pax:3,  range:580,  initK:75,    fixK:14,   varH:72,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Duke B60',            type:'piston',tas:220, pax:5,  range:985, initK:220,   fixK:28,   varH:125,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air 90',         type:'turbo', tas:240, pax:6,  range:1120, initK:900,   fixK:100,  varH:480,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air 100',        type:'turbo', tas:250, pax:8,  range:1205, initK:1200,  fixK:110,  varH:520,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air 200',        type:'turbo', tas:272, pax:9,  range:1414, initK:2000,  fixK:120,  varH:580,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air 250',        type:'turbo', tas:280, pax:9,  range:1580, initK:7400,  fixK:175,  varH:680,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air 300',        type:'turbo', tas:290, pax:9,  range:1655, initK:3500,  fixK:190,  varH:750,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air 350ER',      type:'turbo', tas:312, pax:11, range:2344, initK:8200,  fixK:180,  varH:900,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air 350i',       type:'turbo', tas:310, pax:11, range:1651, initK:7200,  fixK:160,  varH:850,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air A100',       type:'turbo', tas:252, pax:8,  range:1224, initK:1300,  fixK:112,  varH:530,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air A90',        type:'turbo', tas:242, pax:6,  range:1139, initK:950,   fixK:102,  varH:490,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air B100',       type:'turbo', tas:255, pax:8,  range:1272, initK:1400,  fixK:115,  varH:540,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air B90',        type:'turbo', tas:244, pax:6,  range:1158, initK:1000,  fixK:104,  varH:500,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air C90B',       type:'turbo', tas:222, pax:7,  range:859,  initK:1100,  fixK:80,   varH:420,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air C90GTx',     type:'turbo', tas:222, pax:6,  range:1009, initK:2800,  fixK:90,   varH:500,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air E90',        type:'turbo', tas:246, pax:6,  range:1177, initK:1050,  fixK:106,  varH:505,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft King Air F90',        type:'turbo', tas:260, pax:6,  range:1270, initK:1500,  fixK:120,  varH:560,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft Musketeer A23',       type:'piston',tas:118, pax:4,  range:612,  initK:55,    fixK:11,   varH:60,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Beechcraft Premier 1A',          type:'jet',  tas:451, pax:6,  range:1134, initK:4000,  fixK:95,   varH:700,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft Queen Air 65',        type:'piston',tas:205, pax:9,  range:796,  initK:150,   fixK:28,   varH:120,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Queen Air 80',        type:'piston',tas:210, pax:9,  range:822,  initK:165,   fixK:29,   varH:125,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Queen Air B80',       type:'piston',tas:215, pax:9,  range:839, initK:180,   fixK:30,   varH:130,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Sierra A24R',         type:'piston',tas:130, pax:4,  range:752,  initK:80,    fixK:13,   varH:68,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Beechcraft Skipper 77',          type:'piston',tas:100, pax:2,  range:425,  initK:30,    fixK:8,    varH:42,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Beechcraft Sport 150',           type:'piston',tas:120, pax:4,  range:590,  initK:58,    fixK:11,   varH:58,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Beechcraft Staggerwing Model 17',type:'piston',tas:190, pax:4,  range:608,  initK:350,   fixK:30,   varH:130,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Beechcraft Starship 2000',       type:'turbo', tas:335, pax:8,  range:1332, initK:2500,  fixK:220,  varH:900,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Beechcraft Sundowner C23',       type:'piston',tas:120, pax:4,  range:710,  initK:65,    fixK:12,   varH:62,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Beechcraft Travel Air 95',       type:'piston',tas:175, pax:4,  range:769,  initK:70,    fixK:16,   varH:82,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Beechcraft Twin Bonanza D50',    type:'piston',tas:178, pax:5,  range:766,  initK:55,    fixK:15,   varH:80,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  // ── Bellanca ─────────────────────────────────────────────────────
  { name:'Bellanca Citabria',          type:'piston',tas:105, pax:2,  range:321,  initK:30,    fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Bellanca Cruisair',          type:'piston',tas:140, pax:4,  range:595,  initK:40,    fixK:10,   varH:52,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Bellanca Decathlon',         type:'piston',tas:128, pax:2,  range:354,  initK:45,    fixK:9,    varH:42,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Bellanca Super Viking 300',  type:'piston',tas:175, pax:4,  range:849,  initK:75,    fixK:14,   varH:70,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Bellanca Viking 300',        type:'piston',tas:170, pax:4,  range:822,  initK:65,    fixK:13,   varH:68,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  // ── Bombardier ─────────────────────────────────────────────────────
  { name:'Bombardier Challenger 300',  type:'jet',  tas:470, pax:9,  range:2865, initK:14000, fixK:300,  varH:1600, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Challenger 350',  type:'jet',  tas:470, pax:10, range:2965, initK:28000, fixK:500,  varH:2500, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Challenger 604',  type:'jet',  tas:466, pax:12, range:3767, initK:9500,  fixK:400,  varH:2000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Challenger 605',  type:'jet',  tas:470, pax:12, range:3765, initK:22000, fixK:420,  varH:2100, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Challenger 650',  type:'jet',  tas:470, pax:12, range:3765, initK:26000, fixK:440,  varH:2150, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Challenger 850',  type:'jet',  tas:459, pax:14, range:2670, initK:16000, fixK:340,  varH:1750, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Global 5000',     type:'jet',  tas:482, pax:14, range:4959, initK:32000, fixK:650,  varH:3400, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Global 5500',     type:'jet',  tas:488, pax:16, range:5656, initK:52000, fixK:900,  varH:4500, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Global 6000',     type:'jet',  tas:488, pax:17, range:5756, initK:38000, fixK:750,  varH:3900, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Global 6500',     type:'jet',  tas:488, pax:17, range:6356, initK:58000, fixK:1000, varH:5000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Global 7500',     type:'jet',  tas:488, pax:19, range:7456, initK:78000, fixK:1300, varH:6500, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Bombardier Global Express',  type:'jet',  tas:482, pax:14, range:5959, initK:26000, fixK:600,  varH:3200, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Britten ─────────────────────────────────────────────────────
  { name:'Britten Norman Defender',    type:'piston',tas:150, pax:9,  range:788,  initK:450,   fixK:37,   varH:135,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:2 },
  { name:'Britten Norman Islander BN-2',type:'piston',tas:140,pax:9,  range:695,  initK:400,   fixK:35,   varH:130,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:2 },
  { name:'Britten Norman Trislander',  type:'piston',tas:140, pax:17, range:675,  initK:600,   fixK:45,   varH:160,  rating:true,  fuel:'AvGas',  gear:'tricycle',    engines:3 },
  // ── Cessna ─────────────────────────────────────────────────────
  { name:'Cessna 120',                 type:'piston',tas:95,  pax:2,  range:309,  initK:28,    fixK:6,    varH:30,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Cessna 140',                 type:'piston',tas:100, pax:2,  range:345,  initK:32,    fixK:6,    varH:32,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Cessna 150',                 type:'piston',tas:90,  pax:2,  range:332,  initK:30,    fixK:7,    varH:32,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 152',                 type:'piston',tas:100, pax:2,  range:340,  initK:55,    fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 162 Skycatcher',      type:'piston',tas:112, pax:2,  range:386,  initK:110,   fixK:9,    varH:40,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 170',                 type:'piston',tas:110, pax:4,  range:418,  initK:45,    fixK:9,    varH:48,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Cessna 172N Skyhawk',        type:'piston',tas:120, pax:4,  range:530,  initK:110,   fixK:15,   varH:68,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 172R Skyhawk',        type:'piston',tas:122, pax:4,  range:538,  initK:250,   fixK:16,   varH:70,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 172S Skyhawk',        type:'piston',tas:122, pax:4,  range:548,  initK:390,   fixK:16,   varH:72,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 172SP',               type:'piston',tas:122, pax:4,  range:548,  initK:200,   fixK:14,   varH:65,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 175 Skylark',         type:'piston',tas:118, pax:4,  range:512,  initK:60,    fixK:11,   varH:58,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 177 Cardinal',        type:'piston',tas:128, pax:4,  range:704,  initK:75,    fixK:13,   varH:65,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 177RG Cardinal',      type:'piston',tas:145, pax:4,  range:741,  initK:90,    fixK:14,   varH:70,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Cessna 180 Skywagon',        type:'piston',tas:148, pax:6,  range:809,  initK:150,   fixK:16,   varH:78,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Cessna 182 RG Skylane',      type:'piston',tas:148, pax:4,  range:889, initK:95,    fixK:16,   varH:82,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Cessna 182Q Skylane',        type:'piston',tas:143, pax:4,  range:793,  initK:110,   fixK:16,   varH:80,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 182T Skylane',        type:'piston',tas:145, pax:4,  range:806,  initK:430,   fixK:18,   varH:85,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 185 Skywagon',        type:'piston',tas:150, pax:6,  range:838,  initK:220,   fixK:19,   varH:90,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Cessna 188 AgTruck',         type:'piston',tas:110, pax:1,  range:318,  initK:65,    fixK:14,   varH:70,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Cessna 195 Businessliner',   type:'piston',tas:150, pax:5,  range:638,  initK:180,   fixK:20,   varH:95,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Cessna 205 Super Skylane',   type:'piston',tas:145, pax:6,  range:991, initK:70,    fixK:14,   varH:72,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 206H Stationair',     type:'piston',tas:145, pax:6,  range:591,  initK:480,   fixK:20,   varH:95,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 207 Skywagon',        type:'piston',tas:150, pax:8,  range:668,  initK:150,   fixK:22,   varH:98,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna 210 Centurion',       type:'piston',tas:168, pax:6,  range:974, initK:140,   fixK:18,   varH:90,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Cessna 303 Crusader',        type:'piston',tas:200, pax:6,  range:900, initK:230,   fixK:26,   varH:112,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 310R',                type:'piston',tas:195, pax:5,  range:854, initK:150,   fixK:22,   varH:100,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 320 Skyknight',       type:'piston',tas:200, pax:5,  range:850, initK:130,   fixK:22,   varH:100,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 335',                 type:'piston',tas:210, pax:6,  range:992, initK:220,   fixK:26,   varH:115,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 336 Skymaster',       type:'piston',tas:160, pax:5,  range:660,  initK:65,    fixK:15,   varH:75,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:2 },
  { name:'Cessna 337 Skymaster',       type:'piston',tas:167, pax:5,  range:714,  initK:80,    fixK:16,   varH:78,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 340A',                type:'piston',tas:200, pax:5,  range:950, initK:200,   fixK:25,   varH:110,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 401',                 type:'piston',tas:200, pax:8,  range:950, initK:180,   fixK:27,   varH:118,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 402C Businessliner',  type:'piston',tas:185, pax:9,  range:961, initK:250,   fixK:28,   varH:120,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 404 Titan',           type:'piston',tas:210, pax:10, range:1042, initK:320,   fixK:32,   varH:135,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 411',                 type:'piston',tas:215, pax:7,  range:1089, initK:200,   fixK:29,   varH:125,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 414A Chancellor',     type:'piston',tas:200, pax:6,  range:950, initK:280,   fixK:28,   varH:120,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna 421C Golden Eagle',   type:'piston',tas:210, pax:6,  range:1042, initK:350,   fixK:30,   varH:130,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna Caravan 208',         type:'turbo', tas:158, pax:9,  range:771,  initK:2100,  fixK:64,   varH:370,  rating:false, fuel:'Jet-A',  gear:'tricycle',    engines:1 },
  { name:'Cessna Caravan 208 EX',      type:'turbo', tas:165, pax:9,  range:818,  initK:2200,  fixK:65,   varH:380,  rating:false, fuel:'Jet-A',  gear:'tricycle',    engines:1 },
  { name:'Cessna Caravan 208B',        type:'turbo', tas:160, pax:14, range:820,  initK:2600,  fixK:70,   varH:420,  rating:false, fuel:'Jet-A',  gear:'tricycle',    engines:1 },
  { name:'Cessna Citation CJ1',        type:'jet',  tas:389, pax:6,  range:1306, initK:2600,  fixK:100,  varH:650,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Citation CJ2',        type:'jet',  tas:407, pax:7,  range:1409, initK:3800,  fixK:120,  varH:720,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Citation CJ2+',       type:'jet',  tas:413, pax:7,  range:1594, initK:5200,  fixK:140,  varH:780,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Citation CJ4',        type:'jet',  tas:451, pax:9,  range:1939, initK:9500,  fixK:190,  varH:980,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Citation Excel',      type:'jet',  tas:441, pax:9,  range:1680, initK:6500,  fixK:200,  varH:1000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Citation III',        type:'jet',  tas:460, pax:9,  range:2270, initK:2200,  fixK:220,  varH:1150, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Citation M2 Gen2',    type:'jet',   tas:400, pax:7,  range:1350, initK:5200,  fixK:130,  varH:850,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Citation Ultra',      type:'jet',  tas:432, pax:8,  range:1684, initK:2600,  fixK:135,  varH:800,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Citation VII',        type:'jet',  tas:465, pax:9,  range:2588, initK:3200,  fixK:260,  varH:1300, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Conquest I 425',      type:'turbo', tas:261, pax:6,  range:970, initK:900,   fixK:75,   varH:410,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Conquest II 441',     type:'turbo', tas:293, pax:9,  range:1194, initK:1100,  fixK:85,   varH:450,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Cessna Grand Caravan EX',    type:'turbo', tas:175, pax:14, range:982, initK:2500,  fixK:68,   varH:390,  rating:false, fuel:'Jet-A',  gear:'tricycle',    engines:1 },
  { name:'Cessna T206H Turbo Stationair',type:'piston',tas:165,pax:6, range:676,  initK:560,   fixK:22,   varH:105,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cessna T210 Turbo Centurion',type:'piston',tas:185, pax:6,  range:1061, initK:170,   fixK:20,   varH:100,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Cessna T337G Pressurized Skymaster',type:'piston',tas:183,pax:5,range:996,initK:160, fixK:20,  varH:90,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Cessna U206 Stationair',     type:'piston',tas:143, pax:6,  range:573,  initK:180,   fixK:19,   varH:92,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  // ── Cirrus ─────────────────────────────────────────────────────
  { name:'Cirrus SR20',                type:'piston',tas:155, pax:4,  range:684,  initK:380,   fixK:18,   varH:90,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cirrus SR22',                type:'piston',tas:180, pax:4,  range:815,  initK:480,   fixK:22,   varH:105,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cirrus SR22 GTS',            type:'piston',tas:182, pax:4,  range:814,  initK:700,   fixK:26,   varH:112,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cirrus SR22T',               type:'piston',tas:183, pax:4,  range:863, initK:800,   fixK:28,   varH:120,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cirrus SR22T G6',            type:'piston',tas:187, pax:4,  range:909, initK:920,   fixK:29,   varH:122,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Cirrus Vision Jet SF50 G2',  type:'jet',   tas:311, pax:5,  range:1119, initK:3100,  fixK:95,   varH:600,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Cirrus Vision Jet SF50',     type:'jet',   tas:305, pax:5,  range:1048, initK:2800,  fixK:90,   varH:580,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:1 },
  // ── Citation ─────────────────────────────────────────────────────
  { name:'Citation Bravo',             type:'jet',  tas:430, pax:8,  range:1385, initK:3200,  fixK:130,  varH:780,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation CJ3+',              type:'jet',  tas:416, pax:7,  range:1832, initK:8200,  fixK:180,  varH:950,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation Encore+',           type:'jet',  tas:441, pax:8,  range:1655, initK:5500,  fixK:150,  varH:850,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation I SP',              type:'jet',  tas:350, pax:7,  range:925, initK:800,   fixK:80,   varH:600,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation II',                type:'jet',  tas:374, pax:8,  range:1013, initK:1200,  fixK:100,  varH:680,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation Latitude',          type:'jet',  tas:446, pax:9,  range:2477, initK:17500, fixK:280,  varH:1350, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation Longitude',         type:'jet',  tas:476, pax:12, range:3262, initK:26500, fixK:420,  varH:2000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation M2 Gen2',           type:'jet',  tas:400, pax:7,  range:1350, initK:5200,  fixK:130,  varH:800,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation Mustang',           type:'jet',  tas:391, pax:4,  range:954, initK:3000,  fixK:90,   varH:600,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation Sovereign+',        type:'jet',  tas:458, pax:9,  range:2618, initK:13500, fixK:250,  varH:1250, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation V Ultra',           type:'jet',  tas:430, pax:8,  range:1385, initK:2400,  fixK:120,  varH:750,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation X+',                type:'jet',  tas:527, pax:12, range:3196, initK:23000, fixK:380,  varH:1900, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Citation XLS+',              type:'jet',  tas:441, pax:9,  range:1880, initK:11500, fixK:220,  varH:1150, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Columbia ─────────────────────────────────────────────────────
  { name:'Columbia 300',               type:'piston',tas:190, pax:4,  range:908, initK:230,   fixK:17,   varH:88,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Columbia 350',               type:'piston',tas:185, pax:4,  range:861, initK:250,   fixK:18,   varH:90,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Columbia 400 / Cessna TTx',  type:'piston',tas:235, pax:4,  range:924, initK:320,   fixK:20,   varH:100,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  // ── Commander ─────────────────────────────────────────────────────
  { name:'Commander 112',              type:'piston',tas:150, pax:4,  range:588,  initK:65,    fixK:12,   varH:62,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Commander 114',              type:'piston',tas:160, pax:4,  range:660,  initK:75,    fixK:13,   varH:66,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Commander 690B Jetprop',     type:'turbo', tas:286, pax:8,  range:1257, initK:400,   fixK:90,   varH:450,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Commander 900',              type:'turbo', tas:295, pax:9,  range:1402, initK:600,   fixK:100,  varH:480,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Commander 980',              type:'turbo', tas:305, pax:9,  range:1498, initK:750,   fixK:105,  varH:495,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Commander 1000 Jetprop',     type:'turbo', tas:300, pax:9,  range:1450, initK:700,   fixK:110,  varH:500,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── CubCrafters ─────────────────────────────────────────────────────
  { name:'CubCrafters Carbon Cub EX-3',type:'piston',tas:117, pax:2,  range:412,  initK:160,   fixK:10,   varH:44,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'CubCrafters Carbon Cub SS',  type:'piston',tas:95,  pax:2,  range:379,  initK:190,   fixK:10,   varH:45,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'CubCrafters Sport Cub S2',   type:'piston',tas:100, pax:2,  range:345,  initK:150,   fixK:9,    varH:42,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'CubCrafters Top Cub CC18',   type:'piston',tas:110, pax:2,  range:488,  initK:300,   fixK:12,   varH:50,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'CubCrafters XCub',           type:'piston',tas:135, pax:2,  range:769,  initK:420,   fixK:14,   varH:58,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Czech ─────────────────────────────────────────────────────
  { name:'Czech Sport Aircraft PS-28 Cruiser',type:'piston',tas:115,pax:2,range:544,initK:155,  fixK:8,    varH:36,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Czech Sport Aircraft SportCruiser', type:'piston',tas:118,pax:2,range:562,initK:135,  fixK:8,    varH:35,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  // ── Daher ─────────────────────────────────────────────────────
  { name:'Daher TBM 700',              type:'turbo', tas:300, pax:5,  range:1580, initK:2200,  fixK:80,   varH:450,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Daher TBM 850',              type:'turbo', tas:320, pax:5,  range:1505, initK:3200,  fixK:90,   varH:540,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Daher TBM 940',              type:'turbo', tas:330, pax:5,  range:1565, initK:4400,  fixK:100,  varH:590,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  // ── Dassault ─────────────────────────────────────────────────────
  { name:'Dassault Falcon 10X',        type:'jet',  tas:488, pax:16, range:7256, initK:75000, fixK:1300, varH:6200, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Dassault Falcon 2000LXS',    type:'jet',  tas:482, pax:10, range:3759, initK:35000, fixK:620,  varH:3000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Dassault Falcon 50EX',       type:'jet',  tas:470, pax:8,  range:3065, initK:8000,  fixK:200,  varH:1200, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:3 },
  { name:'Dassault Falcon 6X',         type:'jet',  tas:488, pax:12, range:5256, initK:47000, fixK:800,  varH:3800, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Dassault Falcon 7X',         type:'jet',  tas:482, pax:14, range:5709, initK:55000, fixK:900,  varH:4500, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:3 },
  { name:'Dassault Falcon 8X',         type:'jet',  tas:488, pax:16, range:6206, initK:62000, fixK:1000, varH:4900, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:3 },
  { name:'Dassault Falcon 900LX',      type:'jet',  tas:480, pax:12, range:4510, initK:38000, fixK:700,  varH:3200, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:3 },
  // ── DeHavilland ─────────────────────────────────────────────────────
  { name:'DeHavilland Beaver DHC-2',   type:'piston',tas:115, pax:7,  range:364,  initK:450,   fixK:25,   varH:130,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'DeHavilland Dash 8 Q100',    type:'turbo', tas:270, pax:37, range:715,  initK:8000,  fixK:350,  varH:1500, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'DeHavilland Dash 8 Q400',    type:'turbo', tas:360, pax:78, range:920, initK:22000, fixK:600,  varH:2400, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'DeHavilland Otter DHC-3',    type:'piston',tas:130, pax:10, range:542,  initK:650,   fixK:35,   varH:170,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'DeHavilland Twin Otter DHC-6',type:'turbo',tas:170, pax:19, range:735,  initK:3000,  fixK:110,  varH:520,  rating:true,  fuel:'Jet-A',  gear:'tricycle',    engines:2 },
  // ── Diamond ─────────────────────────────────────────────────────
  { name:'Diamond DA20 Katana',        type:'piston',tas:109, pax:2,  range:418,  initK:160,   fixK:10,   varH:50,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Diamond DA40 NG',            type:'piston',tas:145, pax:4,  range:661,  initK:420,   fixK:17,   varH:78,   rating:false, fuel:'Jet-A', gear:'tricycle',    engines:1 },
  { name:'Diamond DA40 XLS',           type:'piston',tas:138, pax:4,  range:646,  initK:380,   fixK:16,   varH:74,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Diamond DA42 Twin Star',     type:'piston',tas:175, pax:4,  range:869, initK:680,   fixK:22,   varH:95,   rating:false, fuel:'Jet-A', gear:'tricycle',    engines:2 },
  { name:'Diamond DA42-VI Twin Star',  type:'piston',tas:185, pax:3,  range:961, initK:750,   fixK:22,   varH:90,   rating:false, fuel:'Jet-A', gear:'tricycle',    engines:2 },
  { name:'Diamond DA50 RG',            type:'piston',tas:190, pax:5,  range:988, initK:900,   fixK:26,   varH:105,  rating:false, fuel:'Jet-A', gear:'retractable', engines:1 },
  { name:'Diamond DA62',               type:'piston',tas:192, pax:6,  range:876, initK:1150,  fixK:32,   varH:115,  rating:false, fuel:'Jet-A', gear:'tricycle',    engines:2 },
  { name:'Diamond DART-450',           type:'turbo', tas:180, pax:2,  range:660,  initK:1400,  fixK:60,   varH:320,  rating:false, fuel:'Jet-A',  gear:'tricycle',    engines:1 },
  // ── Eclipse ─────────────────────────────────────────────────────
  { name:'Eclipse 400',                type:'jet',  tas:370, pax:3,  range:940, initK:2400,  fixK:75,   varH:520,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Eclipse 500',                type:'jet',  tas:370, pax:5,  range:865, initK:2100,  fixK:78,   varH:530,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Eclipse 550',                type:'jet',  tas:375, pax:4,  range:937, initK:2950,  fixK:85,   varH:560,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Embraer ─────────────────────────────────────────────────────
  { name:'Embraer Legacy 450',         type:'jet',  tas:466, pax:9,  range:2667, initK:20000, fixK:380,  varH:1800, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Legacy 500',         type:'jet',  tas:466, pax:12, range:2892, initK:23000, fixK:420,  varH:2000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Legacy 600',         type:'jet',  tas:459, pax:13, range:3170, initK:28000, fixK:500,  varH:2400, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Legacy 650E',        type:'jet',  tas:460, pax:14, range:3670, initK:32000, fixK:540,  varH:2550, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Phenom 100E',        type:'jet',  tas:389, pax:5,  range:984, initK:4500,  fixK:100,  varH:600,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Phenom 100EV',       type:'jet',  tas:390, pax:5,  range:983, initK:4900,  fixK:105,  varH:620,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Phenom 300',         type:'jet',  tas:453, pax:8,  range:1745, initK:8600,  fixK:190,  varH:1020, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Phenom 300E',        type:'jet',  tas:453, pax:8,  range:1784, initK:11500, fixK:200,  varH:1050, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Praetor 500',        type:'jet',  tas:466, pax:9,  range:3107, initK:25000, fixK:450,  varH:2100, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Embraer Praetor 600',        type:'jet',  tas:466, pax:12, range:3785, initK:31000, fixK:550,  varH:2600, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Epic ─────────────────────────────────────────────────────
  { name:'Epic E1000 GX',              type:'turbo', tas:333, pax:5,  range:1434, initK:3500,  fixK:90,   varH:520,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Epic LT',                    type:'turbo', tas:325, pax:6,  range:1338, initK:2000,  fixK:85,   varH:500,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Epic Victory',               type:'jet',   tas:390, pax:5,  range:1105, initK:2800,  fixK:95,   varH:560,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:1 },
  // ── Evektor ─────────────────────────────────────────────────────
  { name:'Evektor Cobra',              type:'piston',tas:105, pax:2,  range:441,  initK:120,   fixK:8,    varH:33,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Evektor Harmony',            type:'piston',tas:108, pax:2,  range:459,  initK:145,   fixK:8,    varH:35,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Evektor SportStar Max',      type:'piston',tas:100, pax:2,  range:425,  initK:140,   fixK:8,    varH:34,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  // ── Extra ─────────────────────────────────────────────────────
  { name:'Extra 200',                  type:'piston',tas:170, pax:1,  range:252,  initK:180,   fixK:11,   varH:52,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Extra 260',                  type:'piston',tas:175, pax:1,  range:259,  initK:210,   fixK:11,   varH:53,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Extra 300L',                 type:'piston',tas:178, pax:2,  range:266,  initK:230,   fixK:12,   varH:54,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Extra 300S',                 type:'piston',tas:180, pax:1,  range:265,  initK:250,   fixK:12,   varH:55,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Extra 330LX',                type:'piston',tas:185, pax:2,  range:361,  initK:380,   fixK:14,   varH:60,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Extra NG',                   type:'piston',tas:190, pax:2,  range:378,  initK:420,   fixK:15,   varH:62,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Fairchild ─────────────────────────────────────────────────────
  { name:'Fairchild Merlin III',       type:'turbo', tas:295, pax:8,  range:1332, initK:320,   fixK:88,   varH:455,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Fairchild Merlin IV',        type:'turbo', tas:280, pax:11, range:1360, initK:500,   fixK:100,  varH:480,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Fairchild Metro III',        type:'turbo', tas:290, pax:19, range:1005, initK:850,   fixK:170,  varH:700,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Fairchild Metro 23',         type:'turbo', tas:300, pax:19, range:1050, initK:1100,  fixK:185,  varH:730,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Glasair ─────────────────────────────────────────────────────
  { name:'Glasair GlaStar',            type:'piston',tas:140, pax:2,  range:645,  initK:70,    fixK:10,   varH:48,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Glasair III',                type:'piston',tas:220, pax:2,  range:1035, initK:80,    fixK:11,   varH:60,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Glasair Sportsman 2+2',      type:'piston',tas:150, pax:4,  range:888, initK:90,    fixK:12,   varH:55,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Glasair Super II RG',        type:'piston',tas:200, pax:2,  range:900, initK:75,    fixK:11,   varH:58,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  // ── Grumman ─────────────────────────────────────────────────────
  { name:'Grumman Albatross HU-16',    type:'piston',tas:205, pax:12, range:2546, initK:200,   fixK:35,   varH:150,  rating:true,  fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Grumman American AA-1 Yankee',type:'piston',tas:120,pax:2,  range:390,  initK:28,    fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Grumman American AA-5 Traveler',type:'piston',tas:125,pax:4,range:466,  initK:35,    fixK:9,    varH:46,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Grumman American AA-5B Tiger',type:'piston',tas:148,pax:4,  range:489,  initK:50,    fixK:10,   varH:55,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Grumman American Cheetah AA-5A',type:'piston',tas:128,pax:4,range:454,  initK:38,    fixK:9,    varH:48,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Grumman Goose G-21',         type:'piston',tas:150, pax:8,  range:528,  initK:280,   fixK:38,   varH:165,  rating:true,  fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Grumman Mallard G-73',       type:'piston',tas:170, pax:10, range:972, initK:380,   fixK:45,   varH:190,  rating:true,  fuel:'AvGas',  gear:'retractable', engines:2 },
  // ── Gulfstream ─────────────────────────────────────────────────────
  { name:'Gulfstream G150',            type:'jet',  tas:459, pax:8,  range:2720, initK:11000, fixK:280,  varH:1450, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G200',            type:'jet',  tas:459, pax:9,  range:3170, initK:9500,  fixK:300,  varH:1500, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G280',            type:'jet',  tas:482, pax:10, range:3359, initK:24000, fixK:450,  varH:2200, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G350',            type:'jet',  tas:476, pax:14, range:3562, initK:26000, fixK:520,  varH:2600, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G450',            type:'jet',  tas:476, pax:16, range:4112, initK:32000, fixK:600,  varH:3000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G500',            type:'jet',  tas:488, pax:19, range:4956, initK:47000, fixK:850,  varH:4200, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G550',            type:'jet',  tas:488, pax:19, range:6506, initK:60000, fixK:1050, varH:5200, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G600',            type:'jet',  tas:488, pax:19, range:6256, initK:58000, fixK:1000, varH:5000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G650',            type:'jet',  tas:488, pax:19, range:6756, initK:68000, fixK:1150, varH:5700, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G650ER',          type:'jet',  tas:488, pax:19, range:7256, initK:72000, fixK:1200, varH:6000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G700',            type:'jet',  tas:488, pax:19, range:7256, initK:82000, fixK:1350, varH:6800, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream G800',            type:'jet',  tas:488, pax:19, range:7756, initK:78000, fixK:1300, varH:6500, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream GIV',             type:'jet',  tas:476, pax:14, range:3982, initK:12000, fixK:550,  varH:2800, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Gulfstream GV',              type:'jet',  tas:488, pax:16, range:6256, initK:20000, fixK:900,  varH:4400, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Hawker ─────────────────────────────────────────────────────
  { name:'Hawker 125-800',             type:'jet',  tas:440, pax:8,  range:2180, initK:2000,  fixK:170,  varH:1050, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Hawker 400XP',               type:'jet',  tas:450, pax:8,  range:955, initK:1900,  fixK:130,  varH:850,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Hawker 700',                 type:'jet',  tas:437, pax:8,  range:2132, initK:1500,  fixK:160,  varH:1000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Hawker 750',                 type:'jet',  tas:447, pax:8,  range:1887, initK:5500,  fixK:200,  varH:1150, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Hawker 800XP',               type:'jet',  tas:447, pax:8,  range:2316, initK:5800,  fixK:210,  varH:1200, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Hawker 850XP',               type:'jet',  tas:448, pax:8,  range:2418, initK:7200,  fixK:220,  varH:1250, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Hawker 900XP',               type:'jet',  tas:448, pax:8,  range:2594, initK:8500,  fixK:240,  varH:1300, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Hawker 1000',                type:'jet',  tas:465, pax:9,  range:3048, initK:3200,  fixK:260,  varH:1350, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Hawker 4000',                type:'jet',  tas:475, pax:8,  range:3042, initK:6500,  fixK:300,  varH:1500, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── HondaJet ─────────────────────────────────────────────────────
  { name:'HondaJet Elite',             type:'jet',  tas:420, pax:6,  range:1190, initK:5300,  fixK:135,  varH:790,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'HondaJet Elite II',          type:'jet',  tas:422, pax:6,  range:1226, initK:5500,  fixK:140,  varH:800,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'HondaJet Elite S',           type:'jet',  tas:425, pax:6,  range:1335, initK:5700,  fixK:142,  varH:810,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── IAI ─────────────────────────────────────────────────────
  { name:'IAI 1125 Astra',             type:'jet',  tas:445, pax:8,  range:2478, initK:2500,  fixK:130,  varH:820,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'IAI Astra SPX',              type:'jet',  tas:450, pax:8,  range:2555, initK:3800,  fixK:140,  varH:850,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'IAI Galaxy 1125',            type:'jet',  tas:459, pax:9,  range:3220, initK:5500,  fixK:180,  varH:950,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'IAI Westwind 1123',          type:'jet',  tas:425, pax:8,  range:1688, initK:600,   fixK:95,   varH:700,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'IAI Westwind 1124',          type:'jet',  tas:430, pax:8,  range:1805, initK:800,   fixK:100,  varH:720,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Icon ─────────────────────────────────────────────────────
  { name:'Icon A5 Amphibious',         type:'piston',tas:84,  pax:2,  range:364,  initK:389,   fixK:14,   varH:45,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  // ── Just ─────────────────────────────────────────────────────
  { name:'Just Aircraft Escapade',     type:'piston',tas:90,  pax:2,  range:332,  initK:52,    fixK:7,    varH:32,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Just Aircraft Highlander',   type:'piston',tas:85,  pax:2,  range:356,  initK:58,    fixK:7,    varH:33,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Just Aircraft SuperSTOL',    type:'piston',tas:78,  pax:2,  range:422,  initK:46,    fixK:7,    varH:31,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Just Aircraft SuperSTOL XL', type:'piston',tas:75,  pax:2,  range:444,  initK:48,    fixK:7,    varH:32,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Kitfox ─────────────────────────────────────────────────────
  { name:'Kitfox Series 5',            type:'piston',tas:95,  pax:2,  range:429,  initK:38,    fixK:7,    varH:30,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Kitfox Series 6',            type:'piston',tas:100, pax:2,  range:475,  initK:45,    fixK:7,    varH:32,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Kitfox Series 7 STi',        type:'piston',tas:105, pax:2,  range:521,  initK:55,    fixK:8,    varH:35,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Kitfox Speedster',           type:'piston',tas:118, pax:2,  range:532,  initK:62,    fixK:8,    varH:36,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Kitfox Super Sport',         type:'piston',tas:110, pax:2,  range:498,  initK:58,    fixK:8,    varH:34,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Lake ─────────────────────────────────────────────────────
  { name:'Lake LA-4 Buccaneer',        type:'piston',tas:120, pax:4,  range:410,  initK:65,    fixK:14,   varH:65,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Lake LA-200 Skimmer',        type:'piston',tas:125, pax:4,  range:456,  initK:85,    fixK:15,   varH:70,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Lake LA-250 Renegade',       type:'piston',tas:130, pax:4,  range:502,  initK:120,   fixK:16,   varH:75,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Lake Renegade Seafury 270',  type:'piston',tas:140, pax:4,  range:545,  initK:170,   fixK:18,   varH:82,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  // ── Lancair ─────────────────────────────────────────────────────
  { name:'Lancair 320',                type:'piston',tas:210, pax:2,  range:642,  initK:60,    fixK:11,   varH:55,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Lancair 360',                type:'piston',tas:225, pax:2,  range:731,  initK:70,    fixK:12,   varH:58,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Lancair ES',                 type:'piston',tas:230, pax:4,  range:828, initK:110,   fixK:13,   varH:60,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Lancair Evolution Piston',   type:'piston',tas:270, pax:4,  range:998, initK:750,   fixK:26,   varH:120,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Lancair Evolution Turbine',  type:'turbo', tas:300, pax:4,  range:1150, initK:1400,  fixK:80,   varH:450,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Lancair IV-P pressurized',   type:'piston',tas:262, pax:4,  range:1151, initK:280,   fixK:20,   varH:95,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Lancair Legacy RG',          type:'piston',tas:240, pax:2,  range:920, initK:120,   fixK:14,   varH:65,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  // ── Learjet ─────────────────────────────────────────────────────
  { name:'Learjet 23',                 type:'jet',  tas:465, pax:6,  range:1268, initK:250,   fixK:110,  varH:750,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 24',                 type:'jet',  tas:465, pax:6,  range:1368, initK:280,   fixK:115,  varH:760,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 25',                 type:'jet',  tas:465, pax:8,  range:1668, initK:320,   fixK:120,  varH:790,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 28',                 type:'jet',  tas:463, pax:8,  range:1868, initK:500,   fixK:130,  varH:820,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 31A',                type:'jet',  tas:464, pax:7,  range:1252, initK:1800,  fixK:130,  varH:800,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 35A',                type:'jet',  tas:464, pax:7,  range:2292, initK:2200,  fixK:150,  varH:880,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 36',                 type:'jet',  tas:464, pax:6,  range:2668, initK:2000,  fixK:150,  varH:870,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 40',                 type:'jet',  tas:464, pax:8,  range:1488, initK:4500,  fixK:170,  varH:900,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 45XR',               type:'jet',  tas:464, pax:9,  range:1968, initK:6000,  fixK:180,  varH:950,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 55C',                type:'jet',  tas:464, pax:8,  range:2418, initK:3500,  fixK:165,  varH:920,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 60XR',               type:'jet',  tas:464, pax:9,  range:2408, initK:7500,  fixK:190,  varH:1000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 70',                 type:'jet',  tas:465, pax:9,  range:1828, initK:11500, fixK:220,  varH:1150, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Learjet 75 Liberty',         type:'jet',  tas:465, pax:9,  range:1808, initK:13000, fixK:240,  varH:1250, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Maule ─────────────────────────────────────────────────────
  { name:'Maule M-4',                  type:'piston',tas:115, pax:4,  range:464,  initK:55,    fixK:10,   varH:48,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Maule M-5-235 Lunar Rocket', type:'piston',tas:130, pax:4,  range:552,  initK:75,    fixK:11,   varH:55,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Maule M-6',                  type:'piston',tas:128, pax:4,  range:544,  initK:80,    fixK:11,   varH:56,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Maule M-7-235 Super Rocket', type:'piston',tas:132, pax:4,  range:601,  initK:185,   fixK:12,   varH:60,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Maule M-9',                  type:'piston',tas:135, pax:4,  range:619,  initK:220,   fixK:13,   varH:62,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Maule MT-7-235',             type:'turbo', tas:170, pax:4,  range:715,  initK:280,   fixK:22,   varH:120,  rating:false, fuel:'Jet-A',  gear:'tailwheel',   engines:1 },
  { name:'Maule MXT-7-180A Star Rocket',type:'piston',tas:130,pax:4,  range:502,  initK:165,   fixK:11,   varH:58,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Mitsubishi ─────────────────────────────────────────────────────
  { name:'Mitsubishi Diamond I',       type:'jet',  tas:440, pax:8,  range:1680, initK:900,   fixK:115,  varH:770,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Mitsubishi Diamond IA',      type:'jet',  tas:445, pax:8,  range:1778, initK:1100,  fixK:120,  varH:780,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Mitsubishi MU-2 Mariner',    type:'turbo', tas:290, pax:6,  range:1005, initK:180,   fixK:62,   varH:350,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Mitsubishi MU-2 Marquise',   type:'turbo', tas:300, pax:8,  range:1150, initK:250,   fixK:70,   varH:380,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Mitsubishi MU-2 Solitaire',  type:'turbo', tas:295, pax:6,  range:1052, initK:200,   fixK:65,   varH:360,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Mitsubishi MU-2B-60',        type:'turbo', tas:310, pax:8,  range:1195, initK:270,   fixK:72,   varH:390,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Mooney ─────────────────────────────────────────────────────
  { name:'Mooney M20 Mark 21',         type:'piston',tas:148, pax:4,  range:739,  initK:38,    fixK:10,   varH:56,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20C Ranger',         type:'piston',tas:150, pax:4,  range:788,  initK:45,    fixK:11,   varH:60,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20E Chaparral',      type:'piston',tas:165, pax:4,  range:826,  initK:60,    fixK:12,   varH:64,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20F Executive',      type:'piston',tas:168, pax:4,  range:854,  initK:65,    fixK:12,   varH:66,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20J 201',            type:'piston',tas:175, pax:4,  range:869, initK:120,   fixK:14,   varH:75,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20K 231',            type:'piston',tas:200, pax:4,  range:900, initK:150,   fixK:16,   varH:80,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20M Bravo',          type:'piston',tas:195, pax:4,  range:954, initK:280,   fixK:18,   varH:88,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20R Ovation 3',      type:'piston',tas:195, pax:4,  range:1054, initK:420,   fixK:20,   varH:95,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20S Eagle',          type:'piston',tas:190, pax:4,  range:1008, initK:350,   fixK:19,   varH:92,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20TN Acclaim S',     type:'piston',tas:220, pax:4,  range:1135, initK:680,   fixK:23,   varH:105,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Mooney M20V Acclaim Ultra',  type:'piston',tas:242, pax:4,  range:1178, initK:750,   fixK:25,   varH:110,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  // ── Phenom ─────────────────────────────────────────────────────
  { name:'Phenom 100',                 type:'jet',  tas:389, pax:5,  range:984, initK:4200,  fixK:98,   varH:600,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Phenom 300E',                type:'jet',  tas:453, pax:10, range:1745, initK:9800,  fixK:200,  varH:1050, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Pilatus ─────────────────────────────────────────────────────
  { name:'Pilatus PC-6 Porter',        type:'turbo', tas:130, pax:10, range:535,  initK:1400,  fixK:80,   varH:420,  rating:false, fuel:'Jet-A',  gear:'tailwheel',   engines:1 },
  { name:'Pilatus PC-7',               type:'turbo', tas:270, pax:2,  range:665,  initK:2200,  fixK:100,  varH:520,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Pilatus PC-9',               type:'turbo', tas:310, pax:2,  range:745,  initK:3500,  fixK:130,  varH:620,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Pilatus PC-12',              type:'turbo', tas:280, pax:9,  range:1560, initK:3800,  fixK:110,  varH:600,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Pilatus PC-12 NG',           type:'turbo', tas:283, pax:9,  range:1658, initK:4300,  fixK:115,  varH:625,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Pilatus PC-12 NGX',          type:'turbo', tas:285, pax:9,  range:1703, initK:4800,  fixK:120,  varH:650,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Pilatus PC-21',              type:'turbo', tas:370, pax:2,  range:615,  initK:12000, fixK:250,  varH:1100, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Pilatus PC-24',              type:'jet',   tas:440, pax:10, range:1780, initK:10500, fixK:210,  varH:1100, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Piper ─────────────────────────────────────────────────────
  { name:'Piper Apache PA-23',         type:'piston',tas:130, pax:3,  range:602,  initK:28,    fixK:12,   varH:65,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Arrow II PA-28R-200',  type:'piston',tas:140, pax:4,  range:615,  initK:95,    fixK:12,   varH:62,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Arrow III PA-28R-201', type:'piston',tas:143, pax:4,  range:633,  initK:110,   fixK:13,   varH:65,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Arrow IV PA-28R-201',  type:'piston',tas:145, pax:4,  range:641,  initK:120,   fixK:13,   varH:68,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Archer III PA-28-181', type:'piston',tas:122, pax:4,  range:428,  initK:170,   fixK:11,   varH:54,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Aztec F PA-23-250',    type:'piston',tas:175, pax:5,  range:999, initK:120,   fixK:22,   varH:100,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Cherokee 140 PA-28-140',type:'piston',tas:112, pax:4, range:396,  initK:42,    fixK:8,    varH:42,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Cherokee 180 PA-28-180',type:'piston',tas:118, pax:4, range:412,  initK:50,    fixK:9,    varH:45,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Cherokee 235 PA-32-260',type:'piston',tas:145, pax:6, range:791,  initK:75,    fixK:15,   varH:75,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Cherokee Six PA-32',   type:'piston',tas:140, pax:6,  range:745,  initK:70,    fixK:14,   varH:72,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Cheyenne 400LS',       type:'turbo', tas:320, pax:9,  range:1900, initK:1400,  fixK:130,  varH:580,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Piper Cheyenne I PA-31T',    type:'turbo', tas:249, pax:7,  range:1076, initK:400,   fixK:75,   varH:400,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Piper Cheyenne II XL',       type:'turbo', tas:283, pax:7,  range:1258, initK:600,   fixK:85,   varH:440,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Piper Cheyenne IIIA',        type:'turbo', tas:290, pax:9,  range:1755, initK:900,   fixK:110,  varH:520,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Piper Colt PA-22-108',       type:'piston',tas:100, pax:2,  range:325,  initK:22,    fixK:6,    varH:28,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Comanche PA-24',       type:'piston',tas:155, pax:4,  range:784,  initK:65,    fixK:12,   varH:65,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Cub PA-11',            type:'piston',tas:75,  pax:2,  range:194,  initK:25,    fixK:5,    varH:22,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Piper Dakota PA-28-236',     type:'piston',tas:140, pax:4,  range:645,  initK:78,    fixK:14,   varH:70,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Lance PA-32R',         type:'piston',tas:148, pax:6,  range:689,  initK:90,    fixK:15,   varH:78,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper M500',                 type:'turbo', tas:260, pax:5,  range:870, initK:2600,  fixK:75,   varH:430,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Piper M600/SLS',             type:'turbo', tas:274, pax:5,  range:1347, initK:3200,  fixK:85,   varH:480,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Piper Malibu Matrix PA-46',  type:'piston',tas:190, pax:6,  range:858, initK:850,   fixK:26,   varH:120,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Malibu Mirage PA-46',  type:'piston',tas:213, pax:6,  range:1183, initK:1100,  fixK:30,   varH:135,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Malibu PA-46-310P',    type:'piston',tas:200, pax:6,  range:1050, initK:650,   fixK:26,   varH:118,  rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Navajo Chieftain PA-31-350',type:'piston',tas:175,pax:9,range:669,initK:300,   fixK:28,   varH:120,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Navajo PA-31-310',     type:'piston',tas:207, pax:7,  range:857, initK:120,   fixK:24,   varH:110,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Navajo Pressurized PA-31P',type:'piston',tas:215,pax:7,range:989,initK:200,   fixK:27,   varH:118,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Pacer PA-20',          type:'piston',tas:105, pax:4,  range:371,  initK:38,    fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Piper Saratoga PA-32R-301',  type:'piston',tas:155, pax:6,  range:734,  initK:180,   fixK:18,   varH:85,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Saratoga Turbo PA-32R-301T',type:'piston',tas:175,pax:6,range:869,initK:220,  fixK:20,   varH:92,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Seminole PA-44',       type:'piston',tas:150, pax:3,  range:588,  initK:170,   fixK:16,   varH:75,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Seneca I PA-34-200',   type:'piston',tas:170, pax:6,  range:672,  initK:110,   fixK:19,   varH:88,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Seneca II PA-34-200T', type:'piston',tas:180, pax:6,  range:715,  initK:150,   fixK:20,   varH:92,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Seneca III PA-34-220T',type:'piston',tas:185, pax:6,  range:741,  initK:280,   fixK:21,   varH:96,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Seneca V PA-34',       type:'piston',tas:190, pax:6,  range:758,  initK:500,   fixK:22,   varH:100,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Super Cub PA-18',      type:'piston',tas:100, pax:2,  range:325,  initK:80,    fixK:7,    varH:28,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Piper Tomahawk PA-38',       type:'piston',tas:100, pax:2,  range:375,  initK:28,    fixK:7,    varH:35,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Tri-Pacer PA-22',      type:'piston',tas:108, pax:4,  range:399,  initK:42,    fixK:8,    varH:40,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Piper Turbo Arrow PA-28RT-201T',type:'piston',tas:158,pax:4,range:682,  initK:130,   fixK:14,   varH:72,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Piper Twin Comanche PA-30',  type:'piston',tas:165, pax:3,  range:646,  initK:60,    fixK:14,   varH:70,   rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },
  { name:'Piper Vagabond PA-15',       type:'piston',tas:90,  pax:2,  range:232,  initK:20,    fixK:5,    varH:22,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Piper Warrior III PA-28-161',type:'piston',tas:110, pax:4,  range:438,  initK:125,   fixK:11,   varH:52,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  // ── Pipistrel ─────────────────────────────────────────────────────
  { name:'Pipistrel Alpha Trainer',    type:'piston',tas:108, pax:2,  range:369,  initK:100,   fixK:7,    varH:26,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Pipistrel Apis',             type:'piston',tas:95,  pax:1,  range:329,  initK:60,    fixK:5,    varH:20,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Pipistrel Panthera',         type:'piston',tas:200, pax:4,  range:850, initK:380,   fixK:14,   varH:65,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Pipistrel Sinus 912',        type:'piston',tas:118, pax:2,  range:712,  initK:140,   fixK:8,    varH:30,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Pipistrel Taurus',           type:'piston',tas:115, pax:2,  range:664,  initK:150,   fixK:8,    varH:29,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Pipistrel Virus SW 121',     type:'piston',tas:130, pax:2,  range:602,  initK:170,   fixK:9,    varH:35,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  // ── Rockwell ─────────────────────────────────────────────────────
  { name:'Rockwell Commander 112',     type:'piston',tas:148, pax:4,  range:589,  initK:55,    fixK:11,   varH:58,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Rockwell Commander 112TC',   type:'piston',tas:168, pax:4,  range:724,  initK:80,    fixK:13,   varH:68,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Rockwell Commander 114',     type:'piston',tas:158, pax:4,  range:682,  initK:70,    fixK:12,   varH:65,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Rockwell Commander 114B',    type:'piston',tas:162, pax:4,  range:698,  initK:85,    fixK:13,   varH:67,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Rockwell Commander 114TC',   type:'piston',tas:180, pax:4,  range:765,  initK:110,   fixK:14,   varH:72,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Rockwell Commander 685',     type:'piston',tas:225, pax:8,  range:1181, initK:200,   fixK:24,   varH:110,  rating:false, fuel:'AvGas',  gear:'retractable', engines:2 },

  // ── Robin ─────────────────────────────────────────────────────
  { name:'Robin DR400/120 Dauphin 2+2',type:'piston',tas:118, pax:4,  range:562,  initK:95,    fixK:11,   varH:52,   rating:false, fuel:'AvGas',  gear:'tricycle',   engines:1 },
  { name:'Robin DR400/140B Major',     type:'piston',tas:125, pax:4,  range:606,  initK:130,   fixK:12,   varH:56,   rating:false, fuel:'AvGas',  gear:'tricycle',   engines:1 },
  { name:'Robin DR400/160 Chevalier',  type:'piston',tas:130, pax:4,  range:652,  initK:150,   fixK:13,   varH:60,   rating:false, fuel:'AvGas',  gear:'tricycle',   engines:1 },
  { name:'Robin DR400/180 Regent',     type:'piston',tas:135, pax:4,  range:699,  initK:175,   fixK:14,   varH:64,   rating:false, fuel:'AvGas',  gear:'tricycle',   engines:1 },
  { name:'Robin DR401',                type:'piston',tas:132, pax:4,  range:681,  initK:190,   fixK:14,   varH:63,   rating:false, fuel:'AvGas',  gear:'tricycle',   engines:1 },
  { name:'Robin DR500 President',      type:'piston',tas:140, pax:4,  range:745,  initK:230,   fixK:15,   varH:68,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Robin HR200',                type:'piston',tas:120, pax:2,  range:410,  initK:105,   fixK:10,   varH:48,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Robin R1180T Aiglon',        type:'piston',tas:145, pax:4,  range:711,  initK:110,   fixK:13,   varH:58,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Robin R2160 Alpha Sport',    type:'piston',tas:128, pax:2,  range:454,  initK:98,    fixK:10,   varH:46,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Robin R3000',                type:'piston',tas:130, pax:2,  range:502,  initK:100,   fixK:10,   varH:47,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },

  // ── Socata ─────────────────────────────────────────────────────
  { name:'Socata MS-880 Rallye Club',  type:'piston',tas:110, pax:4,  range:418,  initK:28,    fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Socata Rallye 235E',         type:'piston',tas:125, pax:4,  range:506,  initK:35,    fixK:9,    varH:45,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Socata TB-9 Tampico',        type:'piston',tas:118, pax:4,  range:562,  initK:52,    fixK:10,   varH:50,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Socata TB-10 Tobago',        type:'piston',tas:125, pax:4,  range:606,  initK:60,    fixK:11,   varH:55,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Socata TB-20 Trinidad',      type:'piston',tas:165, pax:4,  range:876, initK:130,   fixK:15,   varH:70,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Socata TB-21 Trinidad TC',   type:'piston',tas:185, pax:4,  range:961, initK:150,   fixK:16,   varH:78,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Socata TB-200 Tobago XL',    type:'piston',tas:132, pax:4,  range:621,  initK:75,    fixK:12,   varH:58,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Socata TBM 900',             type:'turbo', tas:330, pax:5,  range:1565, initK:4000,  fixK:95,   varH:560,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'Socata TBM 930',             type:'turbo', tas:330, pax:5,  range:1565, initK:4200,  fixK:98,   varH:580,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  // ── Stinson ─────────────────────────────────────────────────────
  { name:'Stinson 10A Voyager',        type:'piston',tas:100, pax:2,  range:325,  initK:28,    fixK:6,    varH:30,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Stinson 108-3 Voyager',      type:'piston',tas:108, pax:4,  range:419,  initK:35,    fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Stinson L-5 Sentinel',       type:'piston',tas:95,  pax:2,  range:329,  initK:30,    fixK:7,    varH:32,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Stinson Reliant SR-10',      type:'piston',tas:135, pax:5,  range:499,  initK:120,   fixK:16,   varH:70,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Swearingen ─────────────────────────────────────────────────────
  { name:'Swearingen Merlin IIB',      type:'turbo', tas:280, pax:6,  range:1210, initK:220,   fixK:75,   varH:410,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Swearingen Merlin III',      type:'turbo', tas:300, pax:8,  range:1390, initK:350,   fixK:90,   varH:460,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Swearingen SA-226 Metro',    type:'turbo', tas:290, pax:19, range:1005, initK:800,   fixK:165,  varH:690,  rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  { name:'Swearingen SJ30',            type:'jet',   tas:490, pax:6,  range:2255, initK:7500,  fixK:190,  varH:1000, rating:true,  fuel:'Jet-A',  gear:'retractable', engines:2 },
  // ── Taylorcraft ─────────────────────────────────────────────────────
  { name:'Taylorcraft BC12-D',         type:'piston',tas:85,  pax:2,  range:236,  initK:18,    fixK:4,    varH:18,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Taylorcraft F19 Sportsman',  type:'piston',tas:105, pax:2,  range:301,  initK:48,    fixK:6,    varH:26,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Taylorcraft F21B',           type:'piston',tas:110, pax:2,  range:318,  initK:55,    fixK:7,    varH:28,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── TBM ─────────────────────────────────────────────────────
  { name:'TBM 700',                    type:'turbo', tas:300, pax:5,  range:1580, initK:2200,  fixK:80,   varH:450,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'TBM 850',                    type:'turbo', tas:320, pax:5,  range:1505, initK:3200,  fixK:90,   varH:540,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'TBM 900',                    type:'turbo', tas:330, pax:5,  range:1565, initK:4000,  fixK:95,   varH:560,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'TBM 910',                    type:'turbo', tas:332, pax:5,  range:1417, initK:4150,  fixK:96,   varH:565,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'TBM 930',                    type:'turbo', tas:330, pax:5,  range:1565, initK:4200,  fixK:98,   varH:580,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'TBM 940',                    type:'turbo', tas:330, pax:5,  range:1565, initK:4400,  fixK:100,  varH:590,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  { name:'TBM 960',                    type:'turbo', tas:330, pax:5,  range:1565, initK:4300,  fixK:100,  varH:600,  rating:false, fuel:'Jet-A',  gear:'retractable', engines:1 },
  // ── Tecnam ─────────────────────────────────────────────────────
  { name:'Tecnam P2002 Sierra',        type:'piston',tas:118, pax:2,  range:512,  initK:150,   fixK:9,    varH:36,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Tecnam P2004 Bravo',         type:'piston',tas:100, pax:2,  range:425,  initK:110,   fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Tecnam P2006T',              type:'piston',tas:140, pax:3,  range:645,  initK:250,   fixK:14,   varH:65,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:2 },
  { name:'Tecnam P2008 JC',            type:'piston',tas:120, pax:2,  range:560,  initK:200,   fixK:10,   varH:44,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Tecnam P2010 MkII',          type:'piston',tas:140, pax:4,  range:610,  initK:370,   fixK:16,   varH:72,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Tecnam P2010 TDI Diesel',    type:'piston',tas:136, pax:4,  range:948, initK:412,   fixK:17,   varH:68,   rating:false, fuel:'Jet-A', gear:'tricycle',    engines:1 },
  { name:'Tecnam P2012 Traveller',     type:'piston',tas:175, pax:11, range:719,  initK:2400,  fixK:110,  varH:480,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:2 },
  { name:'Tecnam P92 Eaglet',          type:'piston',tas:105, pax:2,  range:521,  initK:130,   fixK:9,    varH:42,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Tecnam P96 Golf',            type:'piston',tas:108, pax:2,  range:499,  initK:100,   fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },

  // ── Thrush ─────────────────────────────────────────────────────
  { name:'Thrush 510G',                type:'turbo', tas:145, pax:1,  range:428,  initK:1100,  fixK:65,   varH:380,  rating:false, fuel:'Jet-A',  gear:'tailwheel',   engines:1 },
  { name:'Thrush Commander S2R',       type:'piston',tas:135, pax:1,  range:349,  initK:650,   fixK:45,   varH:280,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Vans ─────────────────────────────────────────────────────
  { name:'Vans RV-3',                  type:'piston',tas:175, pax:1,  range:519,  initK:38,    fixK:7,    varH:36,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Vans RV-4',                  type:'piston',tas:165, pax:2,  range:576,  initK:42,    fixK:8,    varH:37,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Vans RV-6',                  type:'piston',tas:160, pax:2,  range:580,  initK:40,    fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Vans RV-7 homebuilt',        type:'piston',tas:170, pax:2,  range:672,  initK:60,    fixK:9,    varH:40,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Vans RV-8',                  type:'piston',tas:180, pax:2,  range:665,  initK:55,    fixK:9,    varH:42,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Vans RV-9',                  type:'piston',tas:155, pax:2,  range:734,  initK:58,    fixK:8,    varH:38,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Vans RV-10',                 type:'piston',tas:175, pax:4,  range:869, initK:80,    fixK:11,   varH:52,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Vans RV-12',                 type:'piston',tas:105, pax:2,  range:421,  initK:45,    fixK:8,    varH:35,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Vans RV-14',                 type:'piston',tas:190, pax:2,  range:908, initK:90,    fixK:10,   varH:48,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  // ── Vulcanair ─────────────────────────────────────────────────────
  { name:'Vulcanair A-Viator',         type:'piston',tas:150, pax:4,  range:688,  initK:340,   fixK:17,   varH:72,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Vulcanair P.68 Observer 2',  type:'piston',tas:155, pax:6,  range:784,  initK:650,   fixK:22,   varH:95,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:2 },
  { name:'Vulcanair P.68 TC',          type:'piston',tas:175, pax:6,  range:869, initK:750,   fixK:24,   varH:102,  rating:false, fuel:'AvGas',  gear:'tricycle',    engines:2 },
  { name:'Vulcanair V.1.0',            type:'piston',tas:145, pax:4,  range:641,  initK:320,   fixK:16,   varH:70,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },

  // ── Waco ─────────────────────────────────────────────────────
  { name:'Waco Classic YMF-5',         type:'piston',tas:110, pax:3,  range:318,  initK:380,   fixK:24,   varH:110,  rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Waco UPF-7',                 type:'piston',tas:100, pax:2,  range:305,  initK:220,   fixK:20,   varH:95,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },

  // ── Yakovlev ─────────────────────────────────────────────────────
  { name:'Yakovlev Yak-52',            type:'piston',tas:130, pax:2,  range:352,  initK:95,    fixK:14,   varH:75,   rating:false, fuel:'AvGas',  gear:'retractable', engines:1 },
  { name:'Yakovlev Yak-55',            type:'piston',tas:150, pax:1,  range:288,  initK:140,   fixK:15,   varH:80,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  // ── Zenith ─────────────────────────────────────────────────────
  { name:'Zenith CH 601 XL',           type:'piston',tas:95,  pax:2,  range:529,  initK:28,    fixK:6,    varH:26,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Zenith CH 650',              type:'piston',tas:105, pax:2,  range:571,  initK:42,    fixK:7,    varH:29,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Zenith CH 750 Cruzer',       type:'piston',tas:100, pax:2,  range:475,  initK:48,    fixK:7,    varH:31,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Zenith STOL CH 701',         type:'piston',tas:75,  pax:2,  range:344,  initK:35,    fixK:6,    varH:28,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },
  { name:'Zenith STOL CH 750',         type:'piston',tas:80,  pax:2,  range:440,  initK:38,    fixK:7,    varH:30,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },

  // ── Zlin ─────────────────────────────────────────────────────
  { name:'Zlin Z-142',                 type:'piston',tas:120, pax:2,  range:360,  initK:85,    fixK:11,   varH:52,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Zlin Z-242L',                type:'piston',tas:135, pax:2,  range:379,  initK:180,   fixK:13,   varH:62,   rating:false, fuel:'AvGas',  gear:'tricycle',    engines:1 },
  { name:'Zlin Z-526',                 type:'piston',tas:125, pax:2,  range:326,  initK:70,    fixK:10,   varH:48,   rating:false, fuel:'AvGas',  gear:'tailwheel',   engines:1 },

]

export function scoreAircraft(a: Aircraft, params: {
  init: number; fix: number; varH: number
  pax: number; range: number
  jet: boolean; turbo: boolean; piston: boolean
  rY: boolean; rN: boolean
}): number | null {
  if (a.type === 'jet'    && !params.jet)    return null
  if (a.type === 'turbo'  && !params.turbo)  return null
  if (a.type === 'piston' && !params.piston) return null
  if (a.rating  && !params.rY) return null
  if (!a.rating && !params.rN) return null
  if (a.pax < params.pax || a.range < params.range) return null

  let s = 100
  const cr = a.initK / params.init
  if (cr > 1.5) s -= 30 * Math.min(1, cr - 1.5); else s += 10 * (1 - cr)
  const fr = a.fixK / params.fix
  if (fr > 1.5) s -= 20 * Math.min(1, fr - 1.5); else s += 8 * (1 - fr)
  const vr = a.varH / params.varH
  if (vr > 1.5) s -= 20 * Math.min(1, vr - 1.5); else s += 8 * (1 - vr)
  s -= (a.pax - params.pax) * 1.5
  s -= (a.range - params.range) / 200
  return Math.max(0, Math.min(100, s))
}
