// src/lib/airports.ts
// Principal airports worldwide (large international airports)

export type APEntry = { icao: string; name: string; lat: number; lon: number; iata?: string }

export const AIRPORTS: APEntry[] = [
  // ── NORTH AMERICA — USA ──────────────────────────────────
  { icao:'KJFK', iata:'JFK', name:'New York JFK',              lat:40.64,  lon:-73.78  },
  { icao:'KLAX', iata:'LAX', name:'Los Angeles',               lat:33.94,  lon:-118.41 },
  { icao:'KORD', iata:'ORD', name:'Chicago O\'Hare',           lat:41.97,  lon:-87.91  },
  { icao:'KATL', iata:'ATL', name:'Atlanta Hartsfield',        lat:33.64,  lon:-84.43  },
  { icao:'KDFW', iata:'DFW', name:'Dallas Fort Worth',         lat:32.90,  lon:-97.04  },
  { icao:'KSFO', iata:'SFO', name:'San Francisco',             lat:37.62,  lon:-122.38 },
  { icao:'KDEN', iata:'DEN', name:'Denver',                    lat:39.86,  lon:-104.67 },
  { icao:'KMIA', iata:'MIA', name:'Miami',                     lat:25.80,  lon:-80.29  },
  { icao:'KBOS', iata:'BOS', name:'Boston Logan',              lat:42.36,  lon:-71.01  },
  { icao:'KSEA', iata:'SEA', name:'Seattle Tacoma',            lat:47.45,  lon:-122.31 },
  { icao:'KPHX', iata:'PHX', name:'Phoenix Sky Harbor',        lat:33.44,  lon:-112.01 },
  { icao:'KEWR', iata:'EWR', name:'Newark Liberty',            lat:40.69,  lon:-74.17  },
  { icao:'KMSP', iata:'MSP', name:'Minneapolis St Paul',       lat:44.88,  lon:-93.22  },
  { icao:'KDTW', iata:'DTW', name:'Detroit Metro',             lat:42.21,  lon:-83.35  },
  { icao:'KPHL', iata:'PHL', name:'Philadelphia',              lat:39.87,  lon:-75.24  },
  { icao:'KIAH', iata:'IAH', name:'Houston Intercontinental',  lat:29.99,  lon:-95.34  },
  { icao:'KHOU', iata:'HOU', name:'Houston Hobby',             lat:29.65,  lon:-95.28  },
  { icao:'KSLC', iata:'SLC', name:'Salt Lake City',            lat:40.79,  lon:-111.98 },
  { icao:'KDCA', iata:'DCA', name:'Washington Reagan',         lat:38.85,  lon:-77.04  },
  { icao:'KIAD', iata:'IAD', name:'Washington Dulles',         lat:38.95,  lon:-77.46  },
  { icao:'KMCO', iata:'MCO', name:'Orlando',                   lat:28.43,  lon:-81.31  },
  { icao:'KTPA', iata:'TPA', name:'Tampa',                     lat:27.98,  lon:-82.53  },
  { icao:'KSAN', iata:'SAN', name:'San Diego',                 lat:32.73,  lon:-117.19 },
  { icao:'KPDX', iata:'PDX', name:'Portland',                  lat:45.59,  lon:-122.60 },
  { icao:'KAUS', iata:'AUS', name:'Austin Bergstrom',          lat:30.20,  lon:-97.67  },
  { icao:'KBNA', iata:'BNA', name:'Nashville',                 lat:36.12,  lon:-86.68  },
  { icao:'KCLT', iata:'CLT', name:'Charlotte Douglas',         lat:35.21,  lon:-80.94  },
  { icao:'KMSY', iata:'MSY', name:'New Orleans',               lat:29.99,  lon:-90.26  },
  { icao:'KLAS', iata:'LAS', name:'Las Vegas',                 lat:36.08,  lon:-115.15 },
  { icao:'KBWI', iata:'BWI', name:'Baltimore Washington',      lat:39.18,  lon:-76.67  },
  { icao:'KCLE', iata:'CLE', name:'Cleveland Hopkins',         lat:41.41,  lon:-81.85  },
  { icao:'KIND', iata:'IND', name:'Indianapolis',              lat:39.72,  lon:-86.29  },
  { icao:'KCMH', iata:'CMH', name:'Columbus',                  lat:39.99,  lon:-82.89  },
  { icao:'KSTL', iata:'STL', name:'St Louis Lambert',          lat:38.75,  lon:-90.37  },
  { icao:'KMEM', iata:'MEM', name:'Memphis',                   lat:35.04,  lon:-89.98  },
  { icao:'KRDU', iata:'RDU', name:'Raleigh Durham',            lat:35.88,  lon:-78.79  },
  { icao:'KFLL', iata:'FLL', name:'Fort Lauderdale',           lat:26.07,  lon:-80.15  },
  { icao:'KJAX', iata:'JAX', name:'Jacksonville',              lat:30.49,  lon:-81.69  },
  { icao:'KOAK', iata:'OAK', name:'Oakland',                   lat:37.72,  lon:-122.22 },
  { icao:'KSJC', iata:'SJC', name:'San Jose',                  lat:37.36,  lon:-121.93 },
  { icao:'KSMF', iata:'SMF', name:'Sacramento',                lat:38.70,  lon:-121.59 },
  { icao:'KABQ', iata:'ABQ', name:'Albuquerque',               lat:35.04,  lon:-106.61 },
  { icao:'KSAT', iata:'SAT', name:'San Antonio',               lat:29.53,  lon:-98.47  },
  { icao:'KELP', iata:'ELP', name:'El Paso',                   lat:31.81,  lon:-106.38 },
  { icao:'KMKE', iata:'MKE', name:'Milwaukee',                 lat:42.95,  lon:-87.90  },
  { icao:'KPIT', iata:'PIT', name:'Pittsburgh',                lat:40.49,  lon:-80.23  },
  { icao:'KRSW', iata:'RSW', name:'Fort Myers',                lat:26.54,  lon:-81.76  },
  { icao:'KPBI', iata:'PBI', name:'Palm Beach',                lat:26.68,  lon:-80.10  },
  { icao:'KBUF', iata:'BUF', name:'Buffalo Niagara',           lat:42.94,  lon:-78.73  },
  { icao:'KRIC', iata:'RIC', name:'Richmond',                  lat:37.51,  lon:-77.32  },
  { icao:'KBDL', iata:'BDL', name:'Hartford Bradley',          lat:41.94,  lon:-72.68  },
  { icao:'KALB', iata:'ALB', name:'Albany',                    lat:42.75,  lon:-73.80  },
  { icao:'KGRR', iata:'GRR', name:'Grand Rapids',              lat:42.88,  lon:-85.52  },
  { icao:'KTUS', iata:'TUS', name:'Tucson',                    lat:32.12,  lon:-110.94 },
  { icao:'KOKC', iata:'OKC', name:'Oklahoma City',             lat:35.39,  lon:-97.60  },
  { icao:'KTUL', iata:'TUL', name:'Tulsa',                     lat:36.20,  lon:-95.89  },
  { icao:'KOMA', iata:'OMA', name:'Omaha Eppley',              lat:41.30,  lon:-95.89  },
  { icao:'KDSM', iata:'DSM', name:'Des Moines',                lat:41.53,  lon:-93.66  },
  { icao:'KBHM', iata:'BHM', name:'Birmingham Alabama',        lat:33.56,  lon:-86.75  },
  { icao:'KMOB', iata:'MOB', name:'Mobile',                    lat:30.69,  lon:-88.24  },
  { icao:'KSAV', iata:'SAV', name:'Savannah',                  lat:32.13,  lon:-81.20  },
  { icao:'KCHA', iata:'CHA', name:'Chattanooga',               lat:35.04,  lon:-85.20  },
  { icao:'PHNL', iata:'HNL', name:'Honolulu',                  lat:21.32,  lon:-157.92 },
  { icao:'PANC', iata:'ANC', name:'Anchorage',                 lat:61.17,  lon:-149.99 },
  { icao:'KSJC', iata:'SJC', name:'San Jose CA',               lat:37.36,  lon:-121.93 },
  // ── CANADA ───────────────────────────────────────────────
  { icao:'CYYZ', iata:'YYZ', name:'Toronto Pearson',           lat:43.68,  lon:-79.63  },
  { icao:'CYVR', iata:'YVR', name:'Vancouver',                 lat:49.19,  lon:-123.18 },
  { icao:'CYUL', iata:'YUL', name:'Montreal Trudeau',          lat:45.47,  lon:-73.74  },
  { icao:'CYYC', iata:'YYC', name:'Calgary',                   lat:51.13,  lon:-114.01 },
  { icao:'CYEG', iata:'YEG', name:'Edmonton',                  lat:53.31,  lon:-113.58 },
  { icao:'CYOW', iata:'YOW', name:'Ottawa',                    lat:45.32,  lon:-75.67  },
  { icao:'CYWG', iata:'YWG', name:'Winnipeg',                  lat:49.91,  lon:-97.24  },
  { icao:'CYHZ', iata:'YHZ', name:'Halifax',                   lat:44.88,  lon:-63.51  },
  { icao:'CYQB', iata:'YQB', name:'Quebec City',               lat:46.79,  lon:-71.39  },
  { icao:'CYXE', iata:'YXE', name:'Saskatoon',                 lat:52.17,  lon:-106.70 },
  { icao:'CYQR', iata:'YQR', name:'Regina',                    lat:50.43,  lon:-104.67 },
  { icao:'CYYJ', iata:'YYJ', name:'Victoria BC',               lat:48.65,  lon:-123.43 },
  { icao:'CYYT', iata:'YYT', name:'St John\'s Newfoundland',   lat:47.62,  lon:-52.75  },
  // ── MEXICO ───────────────────────────────────────────────
  { icao:'MMMX', iata:'MEX', name:'Mexico City',               lat:19.44,  lon:-99.07  },
  { icao:'MMCUN', iata:'CUN', name:'Cancun',                   lat:21.04,  lon:-86.87  },
  { icao:'MMSD', iata:'SJD', name:'Los Cabos',                 lat:23.15,  lon:-109.72 },
  { icao:'MMPR', iata:'PVR', name:'Puerto Vallarta',           lat:20.68,  lon:-105.25 },
  { icao:'MMGL', iata:'GDL', name:'Guadalajara',               lat:20.52,  lon:-103.31 },
  { icao:'MMMY', iata:'MTY', name:'Monterrey',                 lat:25.78,  lon:-100.11 },
  { icao:'MMTJ', iata:'TIJ', name:'Tijuana',                   lat:32.54,  lon:-116.97 },
  { icao:'MMTO', iata:'TOL', name:'Toluca',                    lat:19.34,  lon:-99.57  },
  { icao:'MMMO', iata:'MLM', name:'Morelia',                   lat:19.85,  lon:-101.02 },
  { icao:'MMVA', iata:'VER', name:'Veracruz',                  lat:19.14,  lon:-96.19  },
  { icao:'MMOX', iata:'OAX', name:'Oaxaca',                    lat:17.00,  lon:-96.73  },
  { icao:'MMCP', iata:'CPE', name:'Campeche',                  lat:19.82,  lon:-90.50  },
  { icao:'MMMD', iata:'MID', name:'Merida',                    lat:20.94,  lon:-89.66  },
  { icao:'MMZC', iata:'ZCL', name:'Zacatecas',                 lat:22.90,  lon:-102.69 },
  // ── CENTRAL AMERICA ──────────────────────────────────────
  { icao:'MROC', iata:'SJO', name:'San Jose Costa Rica',       lat:9.99,   lon:-84.21  },
  { icao:'MGGT', iata:'GUA', name:'Guatemala City',            lat:14.58,  lon:-90.53  },
  { icao:'MHLM', iata:'SAP', name:'San Pedro Sula Honduras',   lat:15.45,  lon:-87.92  },
  { icao:'MHSC', iata:'XPL', name:'Comayagua Honduras',        lat:14.38,  lon:-87.62  },
  { icao:'MSLP', iata:'SAL', name:'San Salvador',              lat:13.44,  lon:-89.06  },
  { icao:'MNMG', iata:'MGA', name:'Managua Nicaragua',         lat:12.14,  lon:-86.17  },
  { icao:'MPTO', iata:'PTY', name:'Panama City Tocumen',       lat:9.07,   lon:-79.38  },
  { icao:'MZBZ', iata:'BZE', name:'Belize City',               lat:17.54,  lon:-88.31  },
  // ── CARIBBEAN ────────────────────────────────────────────
  { icao:'MUHA', iata:'HAV', name:'Havana',                    lat:22.99,  lon:-82.41  },
  { icao:'MDSD', iata:'SDQ', name:'Santo Domingo',             lat:18.43,  lon:-69.67  },
  { icao:'MDPC', iata:'PUJ', name:'Punta Cana',                lat:18.57,  lon:-68.36  },
  { icao:'MKJP', iata:'KIN', name:'Kingston Jamaica',          lat:17.94,  lon:-76.79  },
  { icao:'TNCM', iata:'SXM', name:'Sint Maarten',              lat:18.04,  lon:-63.11  },
  { icao:'TNCA', iata:'AUA', name:'Aruba Oranjestad',          lat:12.50,  lon:-70.01  },
  { icao:'MBPV', iata:'PLS', name:'Providenciales Turks',      lat:21.77,  lon:-72.27  },
  { icao:'MYGF', iata:'FPO', name:'Freeport Bahamas',          lat:26.56,  lon:-78.70  },
  { icao:'MYEF', iata:'GGT', name:'George Town Bahamas',       lat:23.56,  lon:-75.88  },
  { icao:'TFFR', iata:'PTP', name:'Pointe-a-Pitre Guadeloupe', lat:16.27,  lon:-61.53  },
  { icao:'TFFF', iata:'FDF', name:'Fort-de-France Martinique', lat:14.59,  lon:-61.00  },
  { icao:'TUPJ', iata:'EIS', name:'Beef Island BVI',           lat:18.44,  lon:-64.54  },
  { icao:'TISX', iata:'STX', name:'St Croix USVI',             lat:17.70,  lon:-64.80  },
  { icao:'TIST', iata:'STT', name:'St Thomas USVI',            lat:18.34,  lon:-64.97  },
  { icao:'TBPB', iata:'BGI', name:'Bridgetown Barbados',       lat:13.07,  lon:-59.49  },
  { icao:'TTPP', iata:'POS', name:'Port of Spain Trinidad',    lat:10.60,  lon:-61.34  },
  { icao:'TLPC', iata:'SLU', name:'St Lucia Hewanorra',        lat:13.73,  lon:-60.95  },
  { icao:'TGPY', iata:'GND', name:'Grenada',                   lat:12.00,  lon:-61.79  },
  { icao:'TNCB', iata:'BON', name:'Bonaire',                   lat:12.13,  lon:-68.27  },
  // ── SOUTH AMERICA ────────────────────────────────────────
  { icao:'SBGR', iata:'GRU', name:'Sao Paulo Guarulhos',       lat:-23.44, lon:-46.47  },
  { icao:'SBKP', iata:'VCP', name:'Sao Paulo Campinas',        lat:-23.01, lon:-47.13  },
  { icao:'SBGL', iata:'GIG', name:'Rio de Janeiro Galeao',     lat:-22.81, lon:-43.25  },
  { icao:'SBBR', iata:'BSB', name:'Brasilia',                  lat:-15.87, lon:-47.92  },
  { icao:'SBPA', iata:'POA', name:'Porto Alegre',              lat:-29.99, lon:-51.17  },
  { icao:'SBRF', iata:'REC', name:'Recife',                    lat:-8.13,  lon:-34.92  },
  { icao:'SBSV', iata:'SSA', name:'Salvador Bahia',            lat:-12.91, lon:-38.33  },
  { icao:'SBFZ', iata:'FOR', name:'Fortaleza',                 lat:-3.78,  lon:-38.53  },
  { icao:'SBMN', iata:'MAO', name:'Manaus',                    lat:-3.04,  lon:-60.05  },
  { icao:'SBCT', iata:'CWB', name:'Curitiba',                  lat:-25.53, lon:-49.18  },
  { icao:'SBFL', iata:'FLN', name:'Florianopolis',             lat:-27.67, lon:-48.55  },
  { icao:'SBCF', iata:'CNF', name:'Belo Horizonte Confins',    lat:-19.62, lon:-43.97  },
  { icao:'SBBE', iata:'BEL', name:'Belem Para',                lat:-1.38,  lon:-48.48  },
  { icao:'SBGO', iata:'GYN', name:'Goiania',                   lat:-16.63, lon:-49.22  },
  { icao:'SAEZ', iata:'EZE', name:'Buenos Aires Ezeiza',       lat:-34.82, lon:-58.54  },
  { icao:'SABE', iata:'AEP', name:'Buenos Aires Aeroparque',   lat:-34.56, lon:-58.42  },
  { icao:'SAME', iata:'MDZ', name:'Mendoza',                   lat:-32.83, lon:-68.79  },
  { icao:'SACO', iata:'COR', name:'Cordoba Argentina',         lat:-31.32, lon:-64.21  },
  { icao:'SAWH', iata:'USH', name:'Ushuaia',                   lat:-54.84, lon:-68.30  },
  { icao:'SCEL', iata:'SCL', name:'Santiago Chile',            lat:-33.39, lon:-70.79  },
  { icao:'SCAR', iata:'ARI', name:'Arica Chile',               lat:-18.35, lon:-70.34  },
  { icao:'SCIP', iata:'IPC', name:'Easter Island',             lat:-27.16, lon:-109.42 },
  { icao:'SKBO', iata:'BOG', name:'Bogota El Dorado',          lat:4.70,   lon:-74.15  },
  { icao:'SKRG', iata:'MDE', name:'Medellin',                  lat:6.17,   lon:-75.42  },
  { icao:'SKCL', iata:'CLO', name:'Cali Colombia',             lat:3.54,   lon:-76.38  },
  { icao:'SKBQ', iata:'BAQ', name:'Barranquilla',              lat:10.89,  lon:-74.78  },
  { icao:'SKCC', iata:'CUC', name:'Cucuta Colombia',           lat:7.93,   lon:-72.51  },
  { icao:'SEQM', iata:'UIO', name:'Quito Mariscal Sucre',      lat:-0.13,  lon:-78.35  },
  { icao:'SEGU', iata:'GYE', name:'Guayaquil',                 lat:-2.16,  lon:-79.88  },
  { icao:'SPIM', iata:'LIM', name:'Lima Jorge Chavez',         lat:-12.02, lon:-77.11  },
  { icao:'SPZO', iata:'CUZ', name:'Cusco Peru',                lat:-13.54, lon:-71.94  },
  { icao:'SLLP', iata:'LPB', name:'La Paz Bolivia',            lat:-16.51, lon:-68.19  },
  { icao:'SLVR', iata:'VVI', name:'Santa Cruz Bolivia',        lat:-17.64, lon:-63.13  },
  { icao:'SUAA', iata:'MVD', name:'Montevideo',                lat:-34.84, lon:-56.03  },
  { icao:'SGAS', iata:'ASU', name:'Asuncion Paraguay',         lat:-25.24, lon:-57.52  },
  { icao:'SVMI', iata:'CCS', name:'Caracas Venezuela',         lat:10.61,  lon:-66.99  },
  { icao:'SVMG', iata:'PMV', name:'Porlamar Venezuela',        lat:10.91,  lon:-63.97  },
  { icao:'SOCA', iata:'CAY', name:'Cayenne French Guiana',     lat:4.82,   lon:-52.37  },
  { icao:'SMJP', iata:'PBM', name:'Paramaribo Suriname',       lat:5.45,   lon:-55.19  },
  { icao:'SYCJ', iata:'GEO', name:'Georgetown Guyana',         lat:6.50,   lon:-58.25  },
  // ── EUROPE — UK & Ireland ────────────────────────────────
  { icao:'EGLL', iata:'LHR', name:'London Heathrow',           lat:51.48,  lon:-0.46   },
  { icao:'EGKK', iata:'LGW', name:'London Gatwick',            lat:51.15,  lon:-0.19   },
  { icao:'EGLC', iata:'LCY', name:'London City',               lat:51.50,  lon:0.05    },
  { icao:'EGSS', iata:'STN', name:'London Stansted',           lat:51.89,  lon:0.24    },
  { icao:'EGNX', iata:'EMA', name:'East Midlands',             lat:52.83,  lon:-1.33   },
  { icao:'EGCC', iata:'MAN', name:'Manchester',                lat:53.35,  lon:-2.27   },
  { icao:'EGPH', iata:'EDI', name:'Edinburgh',                 lat:55.95,  lon:-3.37   },
  { icao:'EGPF', iata:'GLA', name:'Glasgow',                   lat:55.87,  lon:-4.43   },
  { icao:'EGBB', iata:'BHX', name:'Birmingham UK',             lat:52.45,  lon:-1.75   },
  { icao:'EGGD', iata:'BRS', name:'Bristol',                   lat:51.38,  lon:-2.72   },
  { icao:'EGAA', iata:'BFS', name:'Belfast International',     lat:54.66,  lon:-6.22   },
  { icao:'EGNT', iata:'NCL', name:'Newcastle',                 lat:55.04,  lon:-1.69   },
  { icao:'EGPD', iata:'ABZ', name:'Aberdeen',                  lat:57.20,  lon:-2.20   },
  { icao:'EGHH', iata:'BOH', name:'Bournemouth',               lat:50.78,  lon:-1.84   },
  { icao:'EIDW', iata:'DUB', name:'Dublin',                    lat:53.43,  lon:-6.27   },
  { icao:'EINN', iata:'SNN', name:'Shannon',                   lat:52.70,  lon:-8.92   },
  { icao:'EICK', iata:'ORK', name:'Cork',                      lat:51.84,  lon:-8.49   },
  // ── EUROPE — France ──────────────────────────────────────
  { icao:'LFPG', iata:'CDG', name:'Paris Charles de Gaulle',   lat:49.01,  lon:2.55    },
  { icao:'LFPO', iata:'ORY', name:'Paris Orly',                lat:48.72,  lon:2.38    },
  { icao:'LFMN', iata:'NCE', name:'Nice Cote d\'Azur',         lat:43.66,  lon:7.21    },
  { icao:'LFML', iata:'MRS', name:'Marseille Provence',        lat:43.44,  lon:5.22    },
  { icao:'LFLL', iata:'LYS', name:'Lyon Saint Exupery',        lat:45.72,  lon:5.09    },
  { icao:'LFBO', iata:'TLS', name:'Toulouse Blagnac',          lat:43.63,  lon:1.37    },
  { icao:'LFBD', iata:'BOD', name:'Bordeaux',                  lat:44.83,  lon:-0.72   },
  { icao:'LFST', iata:'SXB', name:'Strasbourg',                lat:48.54,  lon:7.63    },
  { icao:'LFRN', iata:'RNS', name:'Rennes',                    lat:48.07,  lon:-1.73   },
  { icao:'LFKJ', iata:'AJA', name:'Ajaccio Corsica',           lat:41.92,  lon:8.80    },
  { icao:'LFKB', iata:'BIA', name:'Bastia Corsica',            lat:42.55,  lon:9.48    },
  // ── EUROPE — Germany ─────────────────────────────────────
  { icao:'EDDF', iata:'FRA', name:'Frankfurt',                 lat:50.04,  lon:8.56    },
  { icao:'EDDM', iata:'MUC', name:'Munich',                    lat:48.35,  lon:11.78   },
  { icao:'EDDB', iata:'BER', name:'Berlin Brandenburg',        lat:52.35,  lon:13.51   },
  { icao:'EDDH', iata:'HAM', name:'Hamburg',                   lat:53.63,  lon:10.00   },
  { icao:'EDDK', iata:'CGN', name:'Cologne Bonn',              lat:50.87,  lon:7.14    },
  { icao:'EDDL', iata:'DUS', name:'Dusseldorf',                lat:51.29,  lon:6.77    },
  { icao:'EDDS', iata:'STR', name:'Stuttgart',                 lat:48.69,  lon:9.22    },
  { icao:'EDDN', iata:'NUE', name:'Nuremberg',                 lat:49.50,  lon:11.08   },
  { icao:'EDDP', iata:'LEJ', name:'Leipzig Halle',             lat:51.43,  lon:12.24   },
  { icao:'EDDC', iata:'DRS', name:'Dresden',                   lat:51.13,  lon:13.77   },
  { icao:'EDHI', iata:'HAM', name:'Hamburg Finkenwerder',      lat:53.54,  lon:9.84    },
  // ── EUROPE — Spain ───────────────────────────────────────
  { icao:'LEMD', iata:'MAD', name:'Madrid Barajas',            lat:40.47,  lon:-3.56   },
  { icao:'LEBL', iata:'BCN', name:'Barcelona El Prat',         lat:41.30,  lon:2.08    },
  { icao:'LEMG', iata:'AGP', name:'Malaga',                    lat:36.67,  lon:-4.50   },
  { icao:'LEPA', iata:'PMI', name:'Palma de Mallorca',         lat:39.55,  lon:2.74    },
  { icao:'LEAL', iata:'ALC', name:'Alicante',                  lat:38.28,  lon:-0.56   },
  { icao:'LEZL', iata:'SVQ', name:'Seville',                   lat:37.42,  lon:-5.90   },
  { icao:'LEVC', iata:'VLC', name:'Valencia',                  lat:39.49,  lon:-0.48   },
  { icao:'LEBB', iata:'BIO', name:'Bilbao',                    lat:43.30,  lon:-2.91   },
  { icao:'GCLP', iata:'LPA', name:'Gran Canaria',              lat:27.93,  lon:-15.39  },
  { icao:'GCTS', iata:'TFS', name:'Tenerife South',            lat:28.04,  lon:-16.57  },
  { icao:'GCXO', iata:'TFN', name:'Tenerife North',            lat:28.48,  lon:-16.34  },
  { icao:'GCFV', iata:'FUE', name:'Fuerteventura',             lat:28.45,  lon:-13.86  },
  { icao:'GCLA', iata:'SPC', name:'La Palma Canaries',         lat:28.63,  lon:-17.76  },
  { icao:'LXGB', iata:'GIB', name:'Gibraltar',                 lat:36.15,  lon:-5.35   },
  // ── EUROPE — Italy ───────────────────────────────────────
  { icao:'LIRF', iata:'FCO', name:'Rome Fiumicino',            lat:41.80,  lon:12.24   },
  { icao:'LIRA', iata:'CIA', name:'Rome Ciampino',             lat:41.80,  lon:12.59   },
  { icao:'LIMC', iata:'MXP', name:'Milan Malpensa',            lat:45.63,  lon:8.72    },
  { icao:'LIML', iata:'LIN', name:'Milan Linate',              lat:45.45,  lon:9.28    },
  { icao:'LIPZ', iata:'VCE', name:'Venice Marco Polo',         lat:45.50,  lon:12.35   },
  { icao:'LIMF', iata:'TRN', name:'Turin',                     lat:45.20,  lon:7.65    },
  { icao:'LIRN', iata:'NAP', name:'Naples',                    lat:40.88,  lon:14.29   },
  { icao:'LICJ', iata:'PMO', name:'Palermo Sicily',            lat:38.18,  lon:13.10   },
  { icao:'LICC', iata:'CTA', name:'Catania Sicily',            lat:37.47,  lon:15.07   },
  { icao:'LIBR', iata:'BRI', name:'Bari',                      lat:41.14,  lon:16.76   },
  { icao:'LIPE', iata:'BLQ', name:'Bologna',                   lat:44.53,  lon:11.29   },
  { icao:'LIBD', iata:'BDS', name:'Brindisi',                  lat:40.66,  lon:17.94   },
  { icao:'LICT', iata:'TPS', name:'Trapani Sicily',            lat:37.91,  lon:12.49   },
  { icao:'LICA', iata:'REG', name:'Reggio Calabria',           lat:38.07,  lon:15.65   },
  { icao:'LIPQ', iata:'TRS', name:'Trieste',                   lat:45.83,  lon:13.47   },
  // ── EUROPE — Portugal ────────────────────────────────────
  { icao:'LPPT', iata:'LIS', name:'Lisbon',                    lat:38.78,  lon:-9.14   },
  { icao:'LPPR', iata:'OPO', name:'Porto',                     lat:41.24,  lon:-8.68   },
  { icao:'LPFR', iata:'FAO', name:'Faro Algarve',              lat:37.01,  lon:-7.97   },
  { icao:'LPMA', iata:'FNC', name:'Funchal Madeira',           lat:32.70,  lon:-16.77  },
  { icao:'LPPD', iata:'PDL', name:'Ponta Delgada Azores',      lat:37.74,  lon:-25.70  },
  { icao:'LPLA', iata:'TER', name:'Terceira Azores',           lat:38.76,  lon:-27.09  },
  // ── EUROPE — Netherlands & Belgium ──────────────────────
  { icao:'EHAM', iata:'AMS', name:'Amsterdam Schiphol',        lat:52.31,  lon:4.77    },
  { icao:'EBBR', iata:'BRU', name:'Brussels',                  lat:50.90,  lon:4.48    },
  { icao:'ELLX', iata:'LUX', name:'Luxembourg',                lat:49.63,  lon:6.21    },
  // ── EUROPE — Switzerland & Austria ──────────────────────
  { icao:'LSZH', iata:'ZRH', name:'Zurich',                    lat:47.46,  lon:8.55    },
  { icao:'LSGG', iata:'GVA', name:'Geneva',                    lat:46.24,  lon:6.11    },
  { icao:'LSZB', iata:'BRN', name:'Bern',                      lat:46.91,  lon:7.50    },
  { icao:'LOWW', iata:'VIE', name:'Vienna',                    lat:48.11,  lon:16.57   },
  { icao:'LOWI', iata:'INN', name:'Innsbruck',                 lat:47.26,  lon:11.34   },
  { icao:'LOWS', iata:'SZG', name:'Salzburg',                  lat:47.79,  lon:13.00   },
  { icao:'LOWG', iata:'GRZ', name:'Graz',                      lat:46.99,  lon:15.44   },
  // ── EUROPE — Scandinavia ─────────────────────────────────
  { icao:'ENGM', iata:'OSL', name:'Oslo Gardermoen',           lat:60.19,  lon:11.10   },
  { icao:'ESSA', iata:'ARN', name:'Stockholm Arlanda',         lat:59.65,  lon:17.92   },
  { icao:'ESGG', iata:'GOT', name:'Gothenburg',                lat:57.66,  lon:12.29   },
  { icao:'ESMS', iata:'MMX', name:'Malmo',                     lat:55.54,  lon:13.37   },
  { icao:'EKCH', iata:'CPH', name:'Copenhagen',                lat:55.62,  lon:12.65   },
  { icao:'EFHK', iata:'HEL', name:'Helsinki',                  lat:60.32,  lon:24.96   },
  { icao:'BIKF', iata:'KEF', name:'Keflavik Iceland',          lat:63.99,  lon:-22.61  },
  { icao:'BIRK', iata:'RKV', name:'Reykjavik',                 lat:64.13,  lon:-21.94  },
  { icao:'ENTC', iata:'TOS', name:'Tromso Norway',             lat:69.68,  lon:18.92   },
  { icao:'ENBO', iata:'BOO', name:'Bodo Norway',               lat:67.27,  lon:14.36   },
  { icao:'ENVA', iata:'TRD', name:'Trondheim Norway',          lat:63.46,  lon:10.92   },
  { icao:'ENBR', iata:'BGO', name:'Bergen Norway',             lat:60.29,  lon:5.22    },
  { icao:'ESPA', iata:'LLA', name:'Lulea Sweden',              lat:65.54,  lon:22.12   },
  { icao:'ESNZ', iata:'OSD', name:'Ostersund Sweden',          lat:63.19,  lon:14.50   },
  // ── EUROPE — Eastern Europe ──────────────────────────────
  { icao:'EPWA', iata:'WAW', name:'Warsaw Chopin',             lat:52.17,  lon:20.97   },
  { icao:'EPKK', iata:'KRK', name:'Krakow',                   lat:50.08,  lon:19.78   },
  { icao:'EPGD', iata:'GDN', name:'Gdansk',                   lat:54.38,  lon:18.47   },
  { icao:'EPWR', iata:'WRO', name:'Wroclaw',                   lat:51.10,  lon:16.89   },
  { icao:'LKPR', iata:'PRG', name:'Prague',                    lat:50.10,  lon:14.26   },
  { icao:'LHBP', iata:'BUD', name:'Budapest',                  lat:47.43,  lon:19.26   },
  { icao:'LROP', iata:'OTP', name:'Bucharest Otopeni',         lat:44.57,  lon:26.10   },
  { icao:'LBSF', iata:'SOF', name:'Sofia',                     lat:42.70,  lon:23.41   },
  { icao:'LDZA', iata:'ZAG', name:'Zagreb',                    lat:45.74,  lon:16.07   },
  { icao:'LJLJ', iata:'LJU', name:'Ljubljana',                 lat:46.22,  lon:14.46   },
  { icao:'LZIB', iata:'BTS', name:'Bratislava',                lat:48.17,  lon:17.21   },
  { icao:'UKBB', iata:'KBP', name:'Kyiv Boryspil',             lat:50.35,  lon:30.89   },
  { icao:'UKKK', iata:'IEV', name:'Kyiv Zhuliany',             lat:50.40,  lon:30.45   },
  { icao:'UMMS', iata:'MSQ', name:'Minsk',                     lat:53.88,  lon:28.03   },
  { icao:'EVRA', iata:'RIX', name:'Riga Latvia',               lat:56.92,  lon:23.97   },
  { icao:'EYVI', iata:'VNO', name:'Vilnius',                   lat:54.63,  lon:25.29   },
  { icao:'EETN', iata:'TLL', name:'Tallinn',                   lat:59.41,  lon:24.83   },
  { icao:'LWSK', iata:'SKP', name:'Skopje North Macedonia',    lat:41.96,  lon:21.62   },
  { icao:'LATI', iata:'TIA', name:'Tirana Albania',            lat:41.42,  lon:19.72   },
  { icao:'LYPG', iata:'TGD', name:'Podgorica Montenegro',      lat:42.36,  lon:19.25   },
  { icao:'LYBE', iata:'BEG', name:'Belgrade Serbia',           lat:44.82,  lon:20.31   },
  { icao:'LQSA', iata:'SJJ', name:'Sarajevo',                  lat:43.82,  lon:18.33   },
  { icao:'LWOH', iata:'OHD', name:'Ohrid North Macedonia',     lat:41.18,  lon:20.74   },
  // ── EUROPE — Greece & Cyprus ─────────────────────────────
  { icao:'LGAV', iata:'ATH', name:'Athens',                    lat:37.94,  lon:23.94   },
  { icao:'LGTS', iata:'SKG', name:'Thessaloniki',              lat:40.52,  lon:22.97   },
  { icao:'LGIR', iata:'HER', name:'Heraklion Crete',           lat:35.34,  lon:25.18   },
  { icao:'LGKR', iata:'CFU', name:'Corfu',                     lat:39.60,  lon:19.91   },
  { icao:'LGRP', iata:'RHO', name:'Rhodes',                    lat:36.41,  lon:28.09   },
  { icao:'LGMK', iata:'JMK', name:'Mykonos',                   lat:37.43,  lon:25.35   },
  { icao:'LGSR', iata:'JTR', name:'Santorini',                 lat:36.40,  lon:25.48   },
  { icao:'LGZA', iata:'ZTH', name:'Zakynthos',                 lat:37.75,  lon:20.88   },
  { icao:'LGKF', iata:'EFL', name:'Kefalonia',                 lat:38.12,  lon:20.50   },
  { icao:'LGSK', iata:'JSI', name:'Skiathos',                  lat:39.18,  lon:23.51   },
  { icao:'LCPH', iata:'PFO', name:'Paphos Cyprus',             lat:34.72,  lon:32.48   },
  { icao:'LCLK', iata:'LCA', name:'Larnaca Cyprus',            lat:34.87,  lon:33.62   },
  // ── EUROPE — Turkey ──────────────────────────────────────
  { icao:'LTFM', iata:'IST', name:'Istanbul',                  lat:41.27,  lon:28.74   },
  { icao:'LTBA', iata:'SAW', name:'Istanbul Sabiha Gokcen',    lat:40.90,  lon:29.31   },
  { icao:'LTAI', iata:'AYT', name:'Antalya',                   lat:36.90,  lon:30.80   },
  { icao:'LTBJ', iata:'ADB', name:'Izmir',                     lat:38.29,  lon:27.16   },
  { icao:'LTFE', iata:'BJV', name:'Bodrum Milas',              lat:37.25,  lon:27.66   },
  { icao:'LTBS', iata:'DLM', name:'Dalaman',                   lat:36.71,  lon:28.79   },
  { icao:'LTAC', iata:'ESB', name:'Ankara Esenboga',           lat:40.13,  lon:32.99   },
  { icao:'LTCG', iata:'TZX', name:'Trabzon',                   lat:40.99,  lon:39.79   },
  // ── RUSSIA ───────────────────────────────────────────────
  { icao:'UUEE', iata:'SVO', name:'Moscow Sheremetyevo',       lat:55.97,  lon:37.41   },
  { icao:'UUDD', iata:'DME', name:'Moscow Domodedovo',         lat:55.41,  lon:37.90   },
  { icao:'UUWW', iata:'VKO', name:'Moscow Vnukovo',            lat:55.60,  lon:37.26   },
  { icao:'ULLI', iata:'LED', name:'St Petersburg Pulkovo',     lat:59.80,  lon:30.26   },
  { icao:'URSS', iata:'AER', name:'Sochi',                     lat:43.45,  lon:39.96   },
  { icao:'UWWW', iata:'KUF', name:'Samara',                    lat:53.50,  lon:50.16   },
  { icao:'UNNT', iata:'OVB', name:'Novosibirsk',               lat:54.97,  lon:82.65   },
  { icao:'UEEE', iata:'YKS', name:'Yakutsk',                   lat:62.09,  lon:129.77  },
  { icao:'UHWW', iata:'VVO', name:'Vladivostok',               lat:43.40,  lon:132.15  },
  { icao:'UIII', iata:'IKT', name:'Irkutsk',                   lat:52.27,  lon:104.39  },
  { icao:'USSS', iata:'SVX', name:'Yekaterinburg',             lat:56.74,  lon:60.80   },
  { icao:'URKK', iata:'KRR', name:'Krasnodar',                 lat:45.03,  lon:39.17   },
  { icao:'URMM', iata:'MRV', name:'Mineralnye Vody',           lat:44.22,  lon:43.08   },
  { icao:'UTSS', iata:'ASB', name:'Ashgabat Turkmenistan',     lat:37.99,  lon:58.36   },
  // ── CENTRAL ASIA ─────────────────────────────────────────
  { icao:'UAAA', iata:'ALA', name:'Almaty Kazakhstan',         lat:43.35,  lon:77.04   },
  { icao:'UACC', iata:'NQZ', name:'Nur-Sultan Kazakhstan',     lat:51.02,  lon:71.47   },
  { icao:'UTDD', iata:'DYU', name:'Dushanbe Tajikistan',       lat:38.54,  lon:68.83   },
  { icao:'UTTT', iata:'TAS', name:'Tashkent Uzbekistan',       lat:41.26,  lon:69.28   },
  { icao:'UBBB', iata:'GYD', name:'Baku Azerbaijan',           lat:40.47,  lon:50.05   },
  { icao:'UGEE', iata:'EVN', name:'Yerevan Armenia',           lat:40.15,  lon:44.40   },
  { icao:'UGTB', iata:'TBS', name:'Tbilisi Georgia',           lat:41.67,  lon:44.95   },
  { icao:'OAMS', iata:'KBL', name:'Kabul Afghanistan',         lat:34.57,  lon:69.21   },
  // ── MIDDLE EAST ──────────────────────────────────────────
  { icao:'OMDB', iata:'DXB', name:'Dubai',                     lat:25.25,  lon:55.36   },
  { icao:'OMAA', iata:'AUH', name:'Abu Dhabi',                 lat:24.44,  lon:54.65   },
  { icao:'OMDW', iata:'DWC', name:'Dubai World Central',       lat:24.90,  lon:55.17   },
  { icao:'OTHH', iata:'DOH', name:'Doha Hamad',                lat:25.27,  lon:51.61   },
  { icao:'OERK', iata:'RUH', name:'Riyadh King Khalid',        lat:24.96,  lon:46.70   },
  { icao:'OEDF', iata:'DMM', name:'Dammam King Fahd',          lat:26.47,  lon:49.80   },
  { icao:'OEJN', iata:'JED', name:'Jeddah King Abdulaziz',     lat:21.68,  lon:39.16   },
  { icao:'OEMA', iata:'MED', name:'Medina',                    lat:24.55,  lon:39.71   },
  { icao:'OEAB', iata:'AHB', name:'Abha Saudi Arabia',         lat:18.24,  lon:42.66   },
  { icao:'LLBG', iata:'TLV', name:'Tel Aviv Ben Gurion',       lat:32.01,  lon:34.89   },
  { icao:'OKBK', iata:'KWI', name:'Kuwait City',               lat:29.23,  lon:47.97   },
  { icao:'OBBI', iata:'BAH', name:'Bahrain Manama',            lat:26.27,  lon:50.63   },
  { icao:'OOMS', iata:'MCT', name:'Muscat Oman',               lat:23.59,  lon:58.28   },
  { icao:'OOSA', iata:'SLL', name:'Salalah Oman',              lat:17.04,  lon:54.09   },
  { icao:'OLBA', iata:'BEY', name:'Beirut',                    lat:33.82,  lon:35.49   },
  { icao:'ORBI', iata:'BGW', name:'Baghdad',                   lat:33.26,  lon:44.23   },
  { icao:'ORBM', iata:'OSM', name:'Mosul Iraq',                lat:36.31,  lon:43.15   },
  { icao:'ORER', iata:'EBL', name:'Erbil Iraq',                lat:36.24,  lon:43.96   },
  { icao:'OIIE', iata:'IKA', name:'Tehran Imam Khomeini',      lat:35.41,  lon:51.15   },
  { icao:'OIII', iata:'THR', name:'Tehran Mehrabad',           lat:35.69,  lon:51.31   },
  { icao:'OIFM', iata:'IFN', name:'Isfahan Iran',              lat:32.75,  lon:51.86   },
  { icao:'OISS', iata:'SYZ', name:'Shiraz Iran',               lat:29.54,  lon:52.59   },
  { icao:'OIMM', iata:'MHD', name:'Mashhad Iran',              lat:36.24,  lon:59.64   },
  { icao:'OSDI', iata:'DAM', name:'Damascus Syria',            lat:33.41,  lon:36.52   },
  { icao:'OYAA', iata:'ADE', name:'Aden Yemen',                lat:12.83,  lon:45.03   },
  { icao:'OYSN', iata:'SAH', name:'Sanaa Yemen',               lat:15.48,  lon:44.22   },
  { icao:'OJAM', iata:'AMM', name:'Amman Queen Alia',          lat:31.72,  lon:35.99   },
  // ── SOUTH ASIA ───────────────────────────────────────────
  { icao:'VIDP', iata:'DEL', name:'Delhi IGI',                 lat:28.56,  lon:77.10   },
  { icao:'VABB', iata:'BOM', name:'Mumbai Chhatrapati Shivaji',lat:19.09,  lon:72.87   },
  { icao:'VOMM', iata:'MAA', name:'Chennai',                   lat:12.99,  lon:80.18   },
  { icao:'VOBL', iata:'BLR', name:'Bangalore Kempegowda',      lat:13.20,  lon:77.71   },
  { icao:'VOCI', iata:'COK', name:'Kochi Kerala',              lat:10.15,  lon:76.40   },
  { icao:'VOGO', iata:'GOI', name:'Goa',                       lat:15.38,  lon:73.83   },
  { icao:'VECC', iata:'CCU', name:'Kolkata',                   lat:22.65,  lon:88.45   },
  { icao:'VOHY', iata:'HYD', name:'Hyderabad',                 lat:17.23,  lon:78.43   },
  { icao:'VISR', iata:'SXR', name:'Srinagar',                  lat:33.99,  lon:74.77   },
  { icao:'VIAR', iata:'ATQ', name:'Amritsar',                  lat:31.71,  lon:74.80   },
  { icao:'VAAH', iata:'AMD', name:'Ahmedabad',                 lat:23.07,  lon:72.63   },
  { icao:'VIDP', iata:'DEL', name:'Delhi',                     lat:28.56,  lon:77.10   },
  { icao:'VEPT', iata:'PAT', name:'Patna India',               lat:25.60,  lon:85.09   },
  { icao:'VEJH', iata:'JRH', name:'Jorhat India',              lat:26.73,  lon:94.17   },
  { icao:'VEGY', iata:'GAU', name:'Guwahati India',            lat:26.11,  lon:91.59   },
  { icao:'VCBI', iata:'CMB', name:'Colombo Sri Lanka',         lat:7.18,   lon:79.88   },
  { icao:'VNKT', iata:'KTM', name:'Kathmandu Nepal',           lat:27.70,  lon:85.36   },
  { icao:'VGHS', iata:'DAC', name:'Dhaka Bangladesh',          lat:23.84,  lon:90.40   },
  { icao:'VGCB', iata:'CGP', name:'Chittagong Bangladesh',     lat:22.25,  lon:91.81   },
  { icao:'OPKC', iata:'KHI', name:'Karachi Jinnah',            lat:24.91,  lon:67.16   },
  { icao:'OPLA', iata:'LHE', name:'Lahore Allama Iqbal',       lat:31.52,  lon:74.40   },
  { icao:'OPIS', iata:'ISB', name:'Islamabad',                 lat:33.62,  lon:73.10   },
  { icao:'OPPG', iata:'PEW', name:'Peshawar Pakistan',         lat:33.99,  lon:71.51   },
  { icao:'VRMM', iata:'MLE', name:'Male Maldives',             lat:4.19,   lon:73.53   },
  // ── EAST ASIA ────────────────────────────────────────────
  { icao:'RJTT', iata:'HND', name:'Tokyo Haneda',              lat:35.55,  lon:139.78  },
  { icao:'RJAA', iata:'NRT', name:'Tokyo Narita',              lat:35.76,  lon:140.39  },
  { icao:'RJBB', iata:'KIX', name:'Osaka Kansai',              lat:34.43,  lon:135.24  },
  { icao:'RJOO', iata:'ITM', name:'Osaka Itami',               lat:34.79,  lon:135.44  },
  { icao:'RJCC', iata:'CTS', name:'Sapporo New Chitose',       lat:42.77,  lon:141.69  },
  { icao:'RJFF', iata:'FUK', name:'Fukuoka',                   lat:33.58,  lon:130.45  },
  { icao:'RJNN', iata:'NGO', name:'Nagoya Chubu',              lat:34.86,  lon:136.81  },
  { icao:'RJOK', iata:'KCZ', name:'Kochi Japan',               lat:33.55,  lon:133.67  },
  { icao:'RJOR', iata:'TTJ', name:'Tottori Japan',             lat:35.53,  lon:134.17  },
  { icao:'RKSI', iata:'ICN', name:'Seoul Incheon',             lat:37.47,  lon:126.45  },
  { icao:'RKSS', iata:'GMP', name:'Seoul Gimpo',               lat:37.56,  lon:126.80  },
  { icao:'RKPK', iata:'PUS', name:'Busan Gimhae',              lat:35.18,  lon:128.94  },
  { icao:'RCTP', iata:'TPE', name:'Taipei Taoyuan',            lat:25.08,  lon:121.23  },
  { icao:'RCSS', iata:'TSA', name:'Taipei Songshan',           lat:25.07,  lon:121.55  },
  { icao:'RCKH', iata:'KHH', name:'Kaohsiung Taiwan',          lat:22.58,  lon:120.35  },
  { icao:'VHHH', iata:'HKG', name:'Hong Kong',                 lat:22.31,  lon:113.92  },
  { icao:'VMMC', iata:'MFM', name:'Macau',                     lat:22.15,  lon:113.59  },
  { icao:'ZBAA', iata:'PEK', name:'Beijing Capital',           lat:40.08,  lon:116.60  },
  { icao:'ZBAD', iata:'PKX', name:'Beijing Daxing',            lat:39.51,  lon:116.41  },
  { icao:'ZSPD', iata:'PVG', name:'Shanghai Pudong',           lat:31.14,  lon:121.81  },
  { icao:'ZSSS', iata:'SHA', name:'Shanghai Hongqiao',         lat:31.20,  lon:121.34  },
  { icao:'ZGGG', iata:'CAN', name:'Guangzhou Baiyun',          lat:23.39,  lon:113.30  },
  { icao:'ZGSZ', iata:'SZX', name:'Shenzhen',                  lat:22.64,  lon:113.81  },
  { icao:'ZUCK', iata:'CKG', name:'Chongqing Jiangbei',        lat:29.72,  lon:106.64  },
  { icao:'ZUUU', iata:'CTU', name:'Chengdu Shuangliu',         lat:30.57,  lon:103.95  },
  { icao:'ZHCC', iata:'CGO', name:'Zhengzhou Xinzheng',        lat:34.52,  lon:113.84  },
  { icao:'ZHHH', iata:'WUH', name:'Wuhan Tianhe',              lat:30.78,  lon:114.21  },
  { icao:'ZSAM', iata:'XMN', name:'Xiamen Gaoqi',              lat:24.54,  lon:118.13  },
  { icao:'ZSNJ', iata:'NKG', name:'Nanjing Lukou',             lat:31.74,  lon:118.87  },
  { icao:'ZBTJ', iata:'TSN', name:'Tianjin Binhai',            lat:39.12,  lon:117.35  },
  { icao:'ZLXY', iata:'XIY', name:'Xi\'an Xianyang',           lat:34.45,  lon:108.76  },
  { icao:'ZSWX', iata:'WUX', name:'Wuxi Sunan',                lat:31.49,  lon:120.43  },
  { icao:'ZSQD', iata:'TAO', name:'Qingdao Jiaodong',          lat:36.27,  lon:120.37  },
  { icao:'ZYHB', iata:'HRB', name:'Harbin Taiping',            lat:45.62,  lon:126.25  },
  { icao:'ZYCC', iata:'CGQ', name:'Changchun Longjia',         lat:43.90,  lon:125.68  },
  { icao:'ZYTX', iata:'SHE', name:'Shenyang Taoxian',          lat:41.64,  lon:123.49  },
  { icao:'ZLDL', iata:'DLC', name:'Dalian Zhoushuizi',         lat:38.97,  lon:121.54  },
  { icao:'ZGHA', iata:'CSX', name:'Changsha Huanghua',         lat:28.19,  lon:113.22  },
  { icao:'ZSWA', iata:'WNZ', name:'Wenzhou Longwan',           lat:27.91,  lon:120.85  },
  { icao:'ZSFZ', iata:'FOC', name:'Fuzhou Changle',            lat:25.93,  lon:119.66  },
  { icao:'ZGHZ', iata:'HAK', name:'Haikou Meilan',             lat:19.93,  lon:110.46  },
  { icao:'ZGSANYA', iata:'SYX', name:'Sanya Phoenix Hainan',   lat:18.30,  lon:109.41  },
  { icao:'ZULS', iata:'LXA', name:'Lhasa Gonggar Tibet',       lat:29.30,  lon:90.91   },
  { icao:'ZPPP', iata:'KMG', name:'Kunming Changshui',         lat:25.10,  lon:102.93  },
  { icao:'ZUGY', iata:'KWE', name:'Guiyang Longdongbao',       lat:26.54,  lon:106.80  },
  { icao:'ZGNN', iata:'NNG', name:'Nanning Wuxu',              lat:22.61,  lon:108.17  },
  { icao:'ZSNB', iata:'NGB', name:'Ningbo Lishe',              lat:29.83,  lon:121.46  },
  { icao:'ZSHC', iata:'HGH', name:'Hangzhou Xiaoshan',         lat:30.23,  lon:120.43  },
  // ── SOUTHEAST ASIA ───────────────────────────────────────
  { icao:'WSSS', iata:'SIN', name:'Singapore Changi',          lat:1.36,   lon:103.99  },
  { icao:'VTBS', iata:'BKK', name:'Bangkok Suvarnabhumi',      lat:13.69,  lon:100.75  },
  { icao:'VTBD', iata:'DMK', name:'Bangkok Don Mueang',        lat:13.91,  lon:100.61  },
  { icao:'VTSP', iata:'HKT', name:'Phuket',                    lat:8.11,   lon:98.31   },
  { icao:'VTCC', iata:'CNX', name:'Chiang Mai',                lat:18.77,  lon:98.96   },
  { icao:'VTSM', iata:'USM', name:'Koh Samui Thailand',        lat:9.55,   lon:100.06  },
  { icao:'WMKK', iata:'KUL', name:'Kuala Lumpur',              lat:2.75,   lon:101.71  },
  { icao:'WMKP', iata:'PEN', name:'Penang',                    lat:5.30,   lon:100.28  },
  { icao:'WMBT', iata:'BKI', name:'Kota Kinabalu',             lat:5.94,   lon:116.05  },
  { icao:'WBGG', iata:'KCH', name:'Kuching Sarawak',           lat:1.48,   lon:110.34  },
  { icao:'WIII', iata:'CGK', name:'Jakarta Soekarno-Hatta',    lat:-6.13,  lon:106.65  },
  { icao:'WADD', iata:'DPS', name:'Bali Ngurah Rai',           lat:-8.75,  lon:115.17  },
  { icao:'WASS', iata:'SUB', name:'Surabaya Juanda',           lat:-7.38,  lon:112.79  },
  { icao:'WIMM', iata:'MES', name:'Medan Kualanamu',           lat:3.64,   lon:98.89   },
  { icao:'WAMM', iata:'UPG', name:'Makassar Sultan Hasanuddin',lat:-5.06,  lon:119.55  },
  { icao:'WARR', iata:'SUB', name:'Surabaya',                  lat:-7.38,  lon:112.79  },
  { icao:'RPLL', iata:'MNL', name:'Manila Ninoy Aquino',       lat:14.51,  lon:121.02  },
  { icao:'RPVM', iata:'CEB', name:'Cebu Mactan',               lat:10.31,  lon:123.98  },
  { icao:'RPVD', iata:'DVO', name:'Davao Francisco Bangoy',    lat:7.13,   lon:125.65  },
  { icao:'VVTS', iata:'SGN', name:'Ho Chi Minh City',          lat:10.82,  lon:106.66  },
  { icao:'VVNB', iata:'HAN', name:'Hanoi Noi Bai',             lat:21.22,  lon:105.81  },
  { icao:'VVDN', iata:'DAD', name:'Da Nang',                   lat:16.04,  lon:108.20  },
  { icao:'VDPP', iata:'PNH', name:'Phnom Penh Cambodia',       lat:11.55,  lon:104.84  },
  { icao:'VDSR', iata:'REP', name:'Siem Reap Cambodia',        lat:13.41,  lon:103.81  },
  { icao:'VLVT', iata:'VTE', name:'Vientiane Laos',            lat:17.99,  lon:102.56  },
  { icao:'VYYY', iata:'RGN', name:'Yangon Myanmar',            lat:16.91,  lon:96.13   },
  { icao:'WBSB', iata:'BWN', name:'Bandar Seri Begawan Brunei',lat:4.94,   lon:114.93  },
  { icao:'VDPB', iata:'KOS', name:'Sihanoukville Cambodia',    lat:10.58,  lon:103.64  },
  // ── AUSTRALIA & NEW ZEALAND ──────────────────────────────
  { icao:'YSSY', iata:'SYD', name:'Sydney',                    lat:-33.95, lon:151.18  },
  { icao:'YMML', iata:'MEL', name:'Melbourne',                 lat:-37.67, lon:144.84  },
  { icao:'YBBN', iata:'BNE', name:'Brisbane',                  lat:-27.38, lon:153.12  },
  { icao:'YPPH', iata:'PER', name:'Perth',                     lat:-31.94, lon:115.97  },
  { icao:'YPAD', iata:'ADL', name:'Adelaide',                  lat:-34.95, lon:138.53  },
  { icao:'YBCS', iata:'CNS', name:'Cairns',                    lat:-16.89, lon:145.76  },
  { icao:'YBCG', iata:'OOL', name:'Gold Coast',                lat:-28.16, lon:153.50  },
  { icao:'YBTL', iata:'TSV', name:'Townsville',                lat:-19.25, lon:146.77  },
  { icao:'YDLV', iata:'DRW', name:'Darwin',                    lat:-12.41, lon:130.88  },
  { icao:'YBHM', iata:'HTI', name:'Hamilton Island',           lat:-20.36, lon:148.95  },
  { icao:'NZAA', iata:'AKL', name:'Auckland',                  lat:-37.01, lon:174.79  },
  { icao:'NZCH', iata:'CHC', name:'Christchurch',              lat:-43.49, lon:172.53  },
  { icao:'NZWN', iata:'WLG', name:'Wellington',                lat:-41.33, lon:174.81  },
  { icao:'NZQN', iata:'ZQN', name:'Queenstown New Zealand',    lat:-45.02, lon:168.74  },
  { icao:'NZDU', iata:'DUD', name:'Dunedin New Zealand',       lat:-45.93, lon:170.20  },
  // ── PACIFIC ISLANDS ──────────────────────────────────────
  { icao:'NFFN', iata:'NAN', name:'Nadi Fiji',                 lat:-17.76, lon:177.44  },
  { icao:'NGFU', iata:'FUN', name:'Funafuti Tuvalu',           lat:-8.52,  lon:179.20  },
  { icao:'NTAA', iata:'PPT', name:'Papeete Tahiti',            lat:-17.55, lon:-149.61 },
  { icao:'NVVV', iata:'VLI', name:'Port Vila Vanuatu',         lat:-17.70, lon:168.32  },
  { icao:'AGGH', iata:'HIR', name:'Honiara Solomon Islands',   lat:-9.43,  lon:160.05  },
  { icao:'AYPK', iata:'POM', name:'Port Moresby Papua New Guinea',lat:-9.44,lon:147.22 },
  { icao:'PGUM', iata:'GUM', name:'Guam',                      lat:13.48,  lon:144.80  },
  { icao:'PHNL', iata:'HNL', name:'Honolulu Hawaii',           lat:21.32,  lon:-157.92 },
  { icao:'PHOG', iata:'OGG', name:'Maui Kahului',              lat:20.90,  lon:-156.43 },
  // ── AFRICA — North Africa ────────────────────────────────
  { icao:'HECA', iata:'CAI', name:'Cairo',                     lat:30.12,  lon:31.41   },
  { icao:'HESH', iata:'SSH', name:'Sharm el-Sheikh',           lat:27.98,  lon:34.40   },
  { icao:'HEAR', iata:'HRG', name:'Hurghada',                  lat:27.18,  lon:33.80   },
  { icao:'HEAX', iata:'ALY', name:'Alexandria Borg el Arab',   lat:30.92,  lon:29.95   },
  { icao:'DTTA', iata:'TUN', name:'Tunis Carthage',            lat:36.85,  lon:10.23   },
  { icao:'GMMN', iata:'CMN', name:'Casablanca Mohammed V',     lat:33.37,  lon:-7.59   },
  { icao:'GMME', iata:'RBA', name:'Rabat Sale',                lat:34.05,  lon:-6.75   },
  { icao:'GMAD', iata:'AGA', name:'Agadir',                    lat:30.38,  lon:-9.41   },
  { icao:'GMMX', iata:'RAK', name:'Marrakech',                 lat:31.61,  lon:-8.04   },
  { icao:'GMMF', iata:'FEZ', name:'Fez Saiss',                 lat:33.93,  lon:-4.98   },
  { icao:'DAAG', iata:'ALG', name:'Algiers Houari Boumediene', lat:36.69,  lon:3.22    },
  { icao:'DAOO', iata:'ORN', name:'Oran Ahmed Ben Bella',      lat:35.62,  lon:-0.62   },
  { icao:'HLLT', iata:'TIP', name:'Tripoli Libya',             lat:32.66,  lon:13.16   },
  // ── AFRICA — East Africa ─────────────────────────────────
  { icao:'HAAB', iata:'ADD', name:'Addis Ababa Bole',          lat:8.98,   lon:38.80   },
  { icao:'HKJK', iata:'NBO', name:'Nairobi Jomo Kenyatta',     lat:-1.32,  lon:36.93   },
  { icao:'HTDA', iata:'DAR', name:'Dar es Salaam',             lat:-6.88,  lon:39.20   },
  { icao:'HKMO', iata:'MBA', name:'Mombasa',                   lat:-4.03,  lon:39.59   },
  { icao:'HUEN', iata:'EBB', name:'Entebbe Uganda',            lat:0.04,   lon:32.44   },
  { icao:'HRYR', iata:'KGL', name:'Kigali Rwanda',             lat:-1.97,  lon:30.14   },
  { icao:'HBBA', iata:'BJM', name:'Bujumbura Burundi',         lat:-3.32,  lon:29.32   },
  { icao:'HDAM', iata:'JIB', name:'Djibouti',                  lat:11.55,  lon:43.16   },
  { icao:'HCMM', iata:'MGQ', name:'Mogadishu Somalia',         lat:2.01,   lon:45.30   },
  { icao:'HSSS', iata:'KRT', name:'Khartoum Sudan',            lat:15.59,  lon:32.55   },
  { icao:'FMMI', iata:'TNR', name:'Antananarivo Madagascar',   lat:-18.80, lon:47.48   },
  { icao:'FSSS', iata:'SEZ', name:'Seychelles Mahe',           lat:-4.67,  lon:55.52   },
  // ── AFRICA — West Africa ─────────────────────────────────
  { icao:'DNMM', iata:'LOS', name:'Lagos Murtala Muhammed',    lat:6.58,   lon:3.32    },
  { icao:'DNAS', iata:'ABV', name:'Abuja Nigeria',             lat:9.01,   lon:7.26    },
  { icao:'DGAA', iata:'ACC', name:'Accra Kotoka',              lat:5.60,   lon:-0.17   },
  { icao:'DIAP', iata:'ABJ', name:'Abidjan Felix Houphouet',   lat:5.26,   lon:-3.93   },
  { icao:'GOBD', iata:'DSS', name:'Dakar Blaise Diagne',       lat:14.67,  lon:-17.07  },
  { icao:'GBYD', iata:'BJL', name:'Banjul Gambia',             lat:13.34,  lon:-16.65  },
  { icao:'GVNP', iata:'SID', name:'Sal Cape Verde',            lat:16.74,  lon:-22.95  },
  { icao:'GVAC', iata:'RAI', name:'Praia Cape Verde',          lat:14.92,  lon:-23.49  },
  { icao:'DXXX', iata:'LFW', name:'Lome Togo',                 lat:6.17,   lon:1.25    },
  { icao:'DBBB', iata:'COO', name:'Cotonou Benin',             lat:6.36,   lon:2.38    },
  { icao:'GUCY', iata:'CKY', name:'Conakry Guinea',            lat:9.58,   lon:-13.61  },
  { icao:'GFLL', iata:'FNA', name:'Freetown Sierra Leone',     lat:8.62,   lon:-13.20  },
  { icao:'GLRB', iata:'ROB', name:'Monrovia Roberts Liberia',  lat:6.23,   lon:-10.36  },
  { icao:'DRRN', iata:'NIM', name:'Niamey Niger',              lat:13.48,  lon:2.18    },
  { icao:'DFFD', iata:'OUA', name:'Ouagadougou Burkina Faso',  lat:12.35,  lon:-1.51   },
  { icao:'FBSK', iata:'GBE', name:'Gaborone Botswana',         lat:-24.56, lon:25.92   },
  // ── AFRICA — Southern & Central Africa ───────────────────
  { icao:'FAOR', iata:'JNB', name:'Johannesburg OR Tambo',     lat:-26.14, lon:28.24   },
  { icao:'FACT', iata:'CPT', name:'Cape Town',                 lat:-33.96, lon:18.60   },
  { icao:'FALE', iata:'DUR', name:'Durban King Shaka',         lat:-29.62, lon:31.12   },
  { icao:'FAPE', iata:'PLZ', name:'Port Elizabeth Gqeberha',   lat:-33.98, lon:25.62   },
  { icao:'FVHA', iata:'HRE', name:'Harare Zimbabwe',           lat:-17.93, lon:31.09   },
  { icao:'FWKI', iata:'LLW', name:'Lilongwe Malawi',           lat:-13.79, lon:33.78   },
  { icao:'FLKK', iata:'LUN', name:'Lusaka Zambia',             lat:-15.33, lon:28.45   },
  { icao:'FNLU', iata:'LAD', name:'Luanda Angola',             lat:-8.86,  lon:13.23   },
  { icao:'FZAA', iata:'FIH', name:'Kinshasa N\'Djili DRC',     lat:-4.39,  lon:15.44   },
  { icao:'FCBB', iata:'BZV', name:'Brazzaville Congo',         lat:-4.25,  lon:15.25   },
  { icao:'FOON', iata:'LBV', name:'Libreville Gabon',          lat:0.46,   lon:9.41    },
  { icao:'FKKD', iata:'DLA', name:'Douala Cameroon',           lat:4.01,   lon:9.72    },
  { icao:'FKYS', iata:'NSI', name:'Yaounde Nsimalen Cameroon', lat:3.72,   lon:11.55   },
  { icao:'FTTJ', iata:'NDJ', name:'N\'Djamena Chad',           lat:12.13,  lon:15.03   },
  { icao:'FEFF', iata:'BGF', name:'Bangui CAR',                lat:4.40,   lon:18.52   },
  { icao:'FZNA', iata:'GOM', name:'Goma DRC',                  lat:-1.67,  lon:29.24   },
  { icao:'GMFO', iata:'OUD', name:'Oujda Morocco',             lat:34.79,  lon:-1.92   },
]

// Build lookup maps
export const AP_BY_ICAO: Record<string, APEntry> = {}
export const AP_BY_IATA: Record<string, APEntry> = {}
AIRPORTS.forEach(ap => {
  if (!AP_BY_ICAO[ap.icao]) AP_BY_ICAO[ap.icao] = ap
  if (ap.iata && !AP_BY_IATA[ap.iata]) AP_BY_IATA[ap.iata] = ap
})

export function lookupAirport(code: string): APEntry | null {
  if (!code) return null
  const uc = code.trim().toUpperCase()
  if (AP_BY_ICAO[uc]) return AP_BY_ICAO[uc]
  if (AP_BY_IATA[uc]) return AP_BY_IATA[uc]
  const byIcao = AIRPORTS.find(a => a.icao.includes(uc) || uc.includes(a.icao))
  if (byIcao) return byIcao
  const byName = AIRPORTS.find(a => a.name.toUpperCase().includes(uc))
  if (byName) return byName
  return null
}

export function searchAirports(query: string, limit = 8): APEntry[] {
  const q = query.trim().toUpperCase()
  if (q.length < 2) return []
  return AIRPORTS.filter(ap =>
    ap.icao.startsWith(q) ||
    (ap.iata && ap.iata.startsWith(q)) ||
    ap.name.toUpperCase().includes(q)
  ).slice(0, limit)
}
